//错误代码 
DEF_ErrorCode = {
//成功 
ERRORCODE_RESULT_ID_SUCCESS : 0, 
//系统错误 
ERRORCODE_RESULT_ID_FAIL : 1, 
//玩家不存在 
ERRORCODE_ROLE_NOT_EXIST : 3, 
//被迫下线！你的账号正在其他设备上登录 
ERRORCODE_KICK_REQISTER : 4, 
//名字已使用 
ERRORCODE_NAME_USED : 5, 
//文字上限 
ERRORCODE_SEND_WORD_LIMIT : 6, 
//聊天频道出现异常 
ERRORCODE_CHAT_EXCEPTION : 7, 
//物品背包满 
ERRORCODE_BAG_FULL : 8, 
//好友已满 
ERRORCODE_FRIEND_FULL : 9, 
//对方好友已满 
ERRORCODE_PEER_FRIEND_FULL : 10, 
//副本已超过挑战次数 
ERRORCODE_RAID_DEKARON_LIMIT : 11, 
//体力不足够 
ERRORCODE_POWER_NOT_ENOUGH : 12, 
//宝箱奖励已经领取 
ERRORCODE_BOX_REWARD_ALREADY_RECV : 13, 
//扫荡冷却中… 
ERRORCODE_SWEEP_COOLING : 14, 
//星星奖励已领取 
ERRORCODE_STAR_REWARD_RECV : 15, 
//星星数不够 
ERRORCODE_STAR_NOT_ENOUGH : 16, 
//宝箱奖励已经领取 
ERRORCODE_BOX_REWARD_RECV : 17, 
//元宝不足够 
ERRORCODE_YUEN_BAO_NOT_ENOUGH : 19, 
//银币不足够 
ERRORCODE_SILVER_NOT_ENOUGH : 20, 
//武将空间已满 
ERRORCODE_HERO_FULL : 21, 
//装备空间已满 
ERRORCODE_EQUIP_FULL : 22, 
//打完前面的怪物再来打我吧！ 
ERRORCODE_PREV_RAID : 23, 
//等级不足够 
ERRORCODE_LEVEL_NOT_ENOUGH : 24, 
//精力不足够 
ERRORCODE_ENERGY_NOT_ENOUGH : 25, 
//vip商城购买到达上限 
ERRORCODE_VIP_SHOP_LIMIT : 26, 
//声望不足够 
ERRORCODE_PRESTIGE_NOT_ENOUGH : 27, 
//武将不存在 
ERRORCODE_HERO_NOT_EXIST : 28, 
//不可通过消耗材料卡升级 
ERRORCODE_MATERIAL_UP_LEVEL : 29, 
//武将等级不可超过角色等级 
ERRORCODE_HERO_LV_LIMIT : 30, 
//自己不可用作升级材料 
ERRORCODE_NOT_MATERIAL_CARD : 31, 
//升级材料武将不存在 
ERRORCODE_HERO_MATERIAL_NOT_EXIST : 32, 
//升级材料武将重复 
ERRORCODE_HERO_MATERIAL_REPEAT : 33, 
//出阵武将不可作为升级材料 
ERRORCODE_PLAY_HERO_UP_LV_MATERIAL : 34, 
//您的武将突破已经达到上限 
ERRORCODE_HERO_BREAKTHROUGH_LIMIT : 35, 
//突破需求卡牌数量不足 
ERRORCODE_HERO_BREAKTHROUGH_CARD : 36, 
//武将升阶材料卡牌id错误 
ERRORCODE_HERO_SCALA_MATERIAL_ID : 37, 
//上阵武将不可当作突破材料 
ERRORCODE_PLAY_HERO_BREAKTHROUGH_MATERIAL : 38, 
//道具数量不足 
ERRORCODE_PROP_NOT_ENOUGH : 39, 
//前置技能未学习 
ERRORCODE_PREV_SKILL_NOT_STUDY : 40, 
//技能达到满级 
ERRORCODE_SKILL_LEVEL_FULL : 41, 
//技能点不足 
ERRORCODE_SKILL_POINT_NOT_ENOUGH : 42, 
//技能未找到 
ERRORCODE_SKILL_NOT_EXIST : 43, 
//同类型技能不够导致无法洗技能 
ERRORCODE_SAME_SKILL_NOT_EXIST : 44, 
//技能槽位错误 
ERRORCODE_SKILL_SLOT_ERROR : 45, 
//武将培养值超过限制 
ERRORCODE_HERO_CULTURE_VAL_OVERFLOW : 46, 
//洗技能所洗槽位不为空 
ERRORCODE_WASH_SKILL_SLOT_NOT_EMPTY : 47, 
//名将副本次数超过限制 
ERRORCODE_FAMOUS_HERO_LIMIT : 48, 
//三国志奖励已经领取 
ERRORCODE_MIKUNI_ALREADY_RECV : 49, 
//装备不存在 
ERRORCODE_EQUIP_NOT_EXIST : 50, 
//装备强化等级超过限制 
ERRORCODE_EQUIP_STRENGTHEN_LIMIT : 51, 
//装备精练等级超过限制 
ERRORCODE_EQUIP_REFINING_LIMIT : 52, 
//道具类型不对 
ERRORCODE_EQUIP_TYEP_ERROR : 53, 
//武将天命等级已经达到最大 
ERRORCODE_HERO_DESTINY_LIMIT : 54, 
//神将商店购买到达上限 
ERRORCODE_MYSTERY_SHOP_BUY_LIMIT : 56, 
//将魂不足够 
ERRORCODE_HERO_SOLU_NOT_ENOUGH : 57, 
//当前的叛军无法攻击 
ERRORCODE_REBEL_UNABLE_ATTACK : 58, 
//征讨令不足够 
ERRORCODE_CRUSADE_NOT_ENOUGH : 59, 
//没找到叛军奖励ID 
ERRORCODE_REBEL_REWARD_ID_NOT_EXIST : 60, 
//宝物背包已满 
ERRORCODE_TREASURE_BAG_FULL : 61, 
//武将不能被突破 
ERRORCODE_HERO_UNABLE_BREAKTHROUGH : 62, 
//宝物不存在 
ERRORCODE_TREASURE_NOT_EXIST : 63, 
//强化材料宝物重复 
ERRORCODE_STRENGTHEN_MATERIAL_REPEAT : 64, 
//精炼材料宝物数据不足 
ERRORCODE_REFINING_MATERIAL_NOT_ENOUGH : 65, 
//宝物碎片数量不足 
ERRORCODE_TREASURE_CHIP_NOT_ENOUGH : 66, 
//叛军非法，叛军暂无公开(叛军没有开放给好友，但好友已经可以看到) 
ERRORCODE_REBEL_ILLEGAL_OPEN : 67, 
//叛军非法，不是自己好友的叛军 
ERRORCODE_REBEL_ILLEGAL_NOT_FRIEND : 68, 
//宝物已装备 
ERRORCODE_TREASURE_ALREADY_WEAR : 69, 
//该宝物不能被强化或精炼 
ERRORCODE_TREASURE_NON_STRENGTHEN_REFINING : 70, 
//没有足够的功勋 
ERRORCODE_MILITARY_EXPLOITS_NOT_ENOUGH : 71, 
//威名不足够 
ERRORCODE_WAL_MART_NOT_ENOUGH : 72, 
//竞技场排名已更新 
ERRORCODE_ARENA_RANK_CHANGE : 73, 
//装备学习所需道具不足 
ERRORCODE_EQUIP_STUDY_PROP_NOT_ENOUGH : 75, 
//重置技能技能等级非法 
ERRORCODE_RESET_SKILL_LV_ILLEGAL : 76, 
//玩家数据更新中… 
ERRORCODE_PLAYER_DATA_UPDATE : 77, 
//该宝物碎片已被抢夺 
ERRORCODE_TREASURE_CHIP_ALREADY_ROB : 78, 
//玩家已经下线 
ERRORCODE_PLAYER_OFFLINE : 79, 
//对方并不是你的好友 
ERRORCODE_PEER_NOT_FRIEND : 80, 
//将军，你已经买了很多了 
ERRORCODE_BUY_TOO_MUCH : 81, 
//购买此商品需达到竞技场排名才行哦 
ERRORCODE_ARENA_RANK_NOT_ENOUGH : 82, 
//购买此商品需达到三国无双层数才行哦 
ERRORCODE_TOWER_FLOOR_NOT_ENOUGH : 83, 
//日常副本未开放 
ERRORCODE_DAILY_RAID_NOT_OPEN : 84, 
//日常副本的次数已经用完 
ERRORCODE_DAILY_RAID_EXHAUSTION : 85, 
//提升VIP等级才是王道 
ERRORCODE_VIP_LV_NOT_ENOUGH : 86, 
//聊天过于频繁 
ERRORCODE_CHAT_SEND_WORD_OFTEN : 87, 
//活动已经结束 
ERRORCODE_ACTIVITY_IS_OVER : 88, 
//你的月卡已领取 
ERRORCODE_MONTH_CARD_ALREADY_RECV : 89, 
//当前不能拜财神 
ERRORCODE_UNABLE_WORSHIP_MAMMON : 90, 
//日常任务的进度尚未达成 
ERRORCODE_DAILY_TASK_NOT_COMPLETE : 91, 
//此日常任务的奖励已经领取过了哦 
ERRORCODE_DAILY_TASK_REWARD_RECV : 92, 
//任务宝箱已经领取 
ERRORCODE_TASK_BOX_REWARD_RECV : 93, 
//宝箱奖励点数不够 
ERRORCODE_BOX_REWARD_POINT_NOT_ENOUGH : 94, 
//重置次数已达到上限 
ERRORCODE_RESET_COUNT_LIMIT : 95, 
//你已经被禁言 
ERRORCODE_BAN_SPEECH : 96, 
//你的账号当前处于冻结状态 
ERRORCODE_ACCOUNT_FREEZE : 97, 
//武将等级不够 
ERRORCODE_HERO_LEVEL_NOT_ENOUGH : 98, 
//登录超时，请回到登录界面重新登录 
ERRORCODE_LOGIN_TIMEOUT : 99, 
//你暂时无权限登录，请稍后再试 
ERRORCODE_LOGIN_NO_PERMISSIONS : 100, 
//玩家处于免战状态，不能被抢夺 
ERRORCODE_FREE_FIGHT_NOT_ROB : 101, 
//排名达到20名再来挑战竞技场前10吧 
ERRORCODE_ARENA_RIRST20_DEKARON : 102, 
//你输入了错误的礼品码 
ERRORCODE_GIFT_CODE : 103, 
//客户端版本错误 
ERRORCODE_CLIENT_VERSION : 104, 
//您的签名不可超过20个字哦 
ERRORCODE_SIGN_WORD_LIMIT : 105, 
//服务器暂未开放 
ERRORCODE_SERVICE_NOT_OPEN : 107, 
//已经超过基金购买时间，无法购买 
ERRORCODE_FUND_BUY_TIME_EXPIRE : 108, 
//将军，基金不可重复购买 
ERRORCODE_FUND_BUY_REPEAT : 109, 
//玩家暂未购买基金 
ERRORCODE_USER_NOT_BUY_FUND : 110, 
//基金福利领取时间已过期，无法领取 
ERRORCODE_FUND_RECV_TIME_EXPIRE : 111, 
//基金奖励已经领取 
ERRORCODE_FUND_REWARD_ALREADY_RECV : 112, 
//基金福利已经领取 
ERRORCODE_FUND_WELFARE_ALREADY_RECV : 113, 
//基金福利领取条件没有达成 
ERRORCODE_FUND_WELFARE_CONDIT_NOT_ENOUGH : 114, 
//活动奖励条件不可领取 
ERRORCODE_ACTIVITY_REWARD_CONDIT_NOT_RECV : 115, 
//活动奖励兑换物品不足 
ERRORCODE_ACTIVITY_EXCHANGE_NOT_ENOUGH : 116, 
//您已经参与过限购活动了 
ERRORCODE_ATTEND_PURCHASE_LIMITS_ACTIVITY : 117, 
//限购的物品已经被抢购光了 
ERRORCODE_PURCHASE_LIMITS_EXHAUST : 118, 
//活动已经结束 
ERRORCODE_ACTIVITY_FINISH : 119, 
//暴动已经被其他人镇压啦 
ERRORCODE_RIOT_OTHER_REPRESS : 120, 
//该礼品码已过期 
ERRORCODE_GIFT_CODE_EXPIRE : 121, 
//礼品码缺少参数 
ERRORCODE_GIFT_CODE_LACK_PARAM : 122, 
//参数错误 
ERRORCODE_INPUT_PARAM : 123, 
//该礼品码已经失效 
ERRORCODE_GIFT_CODE_INVALID : 124, 
//该礼品码不存在 
ERRORCODE_GIFT_CODE_NOT_EXIST : 126, 
//活动已经过期 
ERRORCODE_ACTIVITY_EXPIRE : 127, 
//该礼品码已经超过了使用次数 
ERRORCODE_GIFT_CODE_USE_LIMIT : 128, 
//活动游戏编码错误 
ERRORCODE_ACTIVITY_CODE : 129, 
//用户名非该绑定用户 
ERRORCODE_USER_NON_BINDING : 130, 
//校验码错误 
ERRORCODE_VERIFY_CODE : 131, 
//军团不存在 
ERRORCODE_LEGION_NOT_EXIST : 132, 
//军团的名称是非法的 
ERRORCODE_LEGION_NAME_INVALID : 133, 
//军团的名称已存在 
ERRORCODE_LEGION_NAME_EXIST : 134, 
//申请的军团已经存在 
ERRORCODE_LEGION_EXIST : 135, 
//您申请的军团数量已达到上限 
ERRORCODE_LEGION_APPLY_LIMIT : 136, 
//您当前处于军团时间冷却中 
ERRORCODE_LEGION_COOLING : 137, 
//军团人数已满 
ERRORCODE_LEGION_ROLE_LIMIT : 138, 
//您的权限不足 
ERRORCODE_NOT_PERMISSION : 139, 
//该玩家已经加入其他的军团 
ERRORCODE_ALREADY_JOINED_OTHER_LEGION : 140, 
//军团的边框条件不满足 
ERRORCODE_LEGION_FRAME_COND_NOT_ENOUGH : 141, 
//军团副军团人数满了 
ERRORCODE_VICE_LEGION_ROLE_LIMIT : 142, 
//军团人数大于最小解散军团人数 
ERRORCODE_LEGION_ROLE_GT_DISSOLVE_ROLE : 143, 
//你已经做过军团贡献了 
ERRORCODE_LEGION_DEVOTE_ALREADY_USE : 144, 
//将军，你已经领过军团贡献奖励 
ERRORCODE_LEGION_DEVOTE_GIFT_ALREADY_RECV : 145, 
//军团贡献奖励点数不足，无法领奖 
ERRORCODE_LEGION_DEVOTE_POINT_NOT_ENOUGH : 146, 
//军团点数不足 
ERRORCODE_LEGION_POINT_NOT_ENOUGH : 147, 
//奖励次数超过限制 
ERRORCODE_REWARD_NUM_LIMIT : 148, 
//全服奖励次数超过限制 
ERRORCODE_ALL_SRV_REWARD_NUM_LIMIT : 149, 
//该奖励不可领取 
ERRORCODE_REWARD_UNABLE_RECV : 150, 
//奖励ID错误 
ERRORCODE_REWARD_ID_ERROR : 151, 
//卡牌数量不足 
ERRORCODE_CARD_NUM_NOT_ENOUGH : 152, 
//装备数量不足 
ERRORCODE_EQUIP_NUM_NOT_ENOUGH : 153, 
//宝物数量不足 
ERRORCODE_TREASURE_NUM_NOT_ENOUGH : 154, 
//奖励领取时间未到 
ERRORCODE_REWARD_TIME_NOT_MEET : 155, 
//弹劾军团长的时间未到 
ERRORCODE_IMPEACH_PRESIDENT_TIME_NOT_MEET : 156, 
//军团长不能退出军团 
ERRORCODE_PRESIDENT_UNABLE_EXIT_LEGION : 157, 
//军团商店的商品不存在，请求已过期 
ERRORCODE_LEGION_SHOP_ITEM_NOT_EXIST : 158, 
//你当前没有加入任何军团 
ERRORCODE_NOT_JOINED_LEGION : 159, 
//你已经加入过军团了 
ERRORCODE_ALREADY_JOINED_LEGION : 160, 
//时装强化等级超过限制 
ERRORCODE_FASHION_STRENGTHEN_LEVEL_LIMIT : 161, 
//时装不存在 
ERRORCODE_FASHION_NOT_EXIST : 162, 
//你已经购买了该道具 
ERRORCODE_ALREADY_BUY_PROP : 163, 
//设置军团章节信息条件不足 
ERRORCODE_SET_LEGION_INFO_NOT_ENOUGH : 164, 
//已经达到最大军团副本的执行次数 
ERRORCODE_LEGION_RAID_LIMIT : 165, 
//军团副本信息错误，信息已过期 
ERRORCODE_LEGION_RAID_INFO_EXPIRE : 166, 
//军团副本已经结束 
ERRORCODE_LEGION_RAID_FINISH : 167, 
//军团副本没有通过 
ERRORCODE_LEGION_RAID_NOT_PASS : 168, 
//您没有军团副本的奖励 
ERRORCODE_LEGION_RAID_REWARD_NOT_EXIST : 169, 
//您已经领取过军团副本奖励 
ERRORCODE_LEGION_RAID_REWARD_ALREADY_RECV : 170, 
//节日活动领奖次数超过限制 
ERRORCODE_FEAST_ACTIVITY_REWARD_LIMIT : 171, 
//节日活动暂未开放 
ERRORCODE_FEAST_ACTIVITY_NOT_OPEN : 172, 
//此道具已过期 
ERRORCODE_PROP_EXPIRE : 173, 
//该宝箱已经被别人捷足先登了 
ERRORCODE_BOX_OTHER_RECV : 174, 
//非法军团对外公告 
ERRORCODE_ILLEGAL_LEGION_OUTSIDE_NOTICY : 175, 
//非法军团对内公告 
ERRORCODE_ILLEGAL_LEGION_INSIDE_NOTICY : 176, 
//礼品码的操作过快 
ERRORCODE_GIFT_CODE_TOO_FAST : 177, 
//当前正处在军团时间冷却中 
ERRORCODE_LEGION_TIME_COOLING : 178, 
//玩家军团申请不存在 
ERRORCODE_LEGION_APPLY_NOT_EXIST : 179, 
//军团祭天已达到最大值 
ERRORCODE_LEGION_WORSHIP_LIMIT : 180, 
//服务器已经达到承载上限 
ERRORCODE_SERVER_LIMIT : 181, 
//军团商城物品已经售完 
ERRORCODE_LEGION_SHOP_SELL_OUT : 182, 
//将军，军团在创建24小时无法解散 
ERRORCODE_LEGION_CREATE_DAILY_NOT_DISSOLVE : 183, 
//无法购买日常副本次数 
ERRORCODE_UNABLE_BUY_DAILY_RAID_NUM : 184, 
//充返活动已经结束 
ERRORCODE_RECHARGE_REBATE_ACT_FINISH : 185, 
//请求过于频繁 
ERRORCODE_REQUEST_TOO_OFTEN : 186, 
//无法领取奖励，因为你在其他服务器已经领取过 
ERRORCODE_OTHER_SERVER_ALREADY_RECVB : 187, 
//充返领取失败 
ERRORCODE_RECHARGE_REBATE_RECV_FAILED : 188, 
//觉醒装备包裹已满 
ERRORCODE_AWAKEN_BAG_FULL : 189, 
//转盘积分不足 
ERRORCODE_TURNTABLE_SCORE_NOT_ENOUGH : 190, 
//转盘总积分不足 
ERRORCODE_TURNTABLE_ALL_SCORE_NOT_ENOUGH : 191, 
//觉醒装备数量不足 
ERRORCODE_AWAKEN_EQUIP_NUM_NOT_ENOUGH : 192, 
//武将不能觉醒 
ERRORCODE_HERO_UNABLE_AWAKEN : 193, 
//武将觉醒装备位置不对 
ERRORCODE_HERO_AWAKEN_EQUIP_POS_ERROR : 194, 
//该觉醒装备已经不存在 
ERRORCODE_AWAKEN_EQUIP_NOT_EXIST : 195, 
//武将觉醒等级已超过限制 
ERRORCODE_AWAKEN_LEVEL_LIMIT : 196, 
//武将觉醒道具未集齐 
ERRORCODE_HERO_AWAKEN_EQUIP_NOT_ALL : 197, 
//武将觉醒材料卡牌数量不足 
ERRORCODE_AWAKEN_MATERIAL_NOT_ENOUGH : 198, 
//武将觉醒材料卡牌错误 
ERRORCODE_AWAKEN_MATERIALERR : 199, 
//上阵武将不可作为觉醒材料 
ERRORCODE_PLAY_HERO_AWAKEN_MATERIAL : 200, 
//您没有足够的神魂 
ERRORCODE_GOD_SOUL_NOT_ENOUGH : 201, 
//该军团申请已满 
ERRORCODE_LEGION_APPLY_FULL : 202, 
//军团副本购买次数达到上限 
ERRORCODE_LEGION_RAID_BUY_LIMIT : 203, 
//称号已装备 
ERRORCODE_EPITHET_ALREADY_WEAR : 204, 
//称号已过期 
ERRORCODE_EPITHET_ALREADY_EXPIRE : 205, 
//比武勋章不足够 
ERRORCODE_MEDAL_NOT_ENOUGH : 206, 
//比武连胜次数不足 
ERRORCODE_JOUST_WINNING_STREAK_NOT_ENOUGH : 208, 
//限时副本未开放 
ERRORCODE_TIMED_RAID_NOT_OPEN : 209, 
//限时副本挑战已完成 
ERRORCODE_TIMED_RAID_DEKARON_FINISH : 210, 
//转盘活动已结束 
ERRORCODE_TURNTABLE_ACTIVITY_FINISH : 211, 
//大富翁活动已结束 
ERRORCODE_RICHMAN_ACTIVITY_FINISH : 212, 
//未知价格类型 
ERRORCODE_UNKNOW_PRICE_TYPE : 213, 
//当前没有活动开启 
ERRORCODE_NOT_ACTIVITY_ON : 214, 
//玩家不在线或不存在 
ERRORCODE_PLAYER_OFFLINE_OR_NOT_EXIST : 215, 
//邮件长度超长 
ERRORCODE_MAIL_LEN_LIMIT : 216, 
//精英副本状态错误 
ERRORCODE_ELITE_RAID_STATE_ERR : 217, 
//你的战斗请求过于频繁 
ERRORCODE_FIGHT_FREQUENTLY : 218, 
//玩家数据需要恢复 
ERRORCODE_PLAYER_DATA_NEED_RESET : 219, 
//你建立的小号数量已经达到了上限 
ERRORCODE_ACCOUNT_NUM_LIMIT : 220, 
//客户端请求错误 
ERRORCODE_CLIENT_REQUEST_ERR : 221, 
//叛军boss活动暂未开启 
ERRORCODE_REBEL_BOSS_NOT_OPEN : 222, 
//你的挑战次数不足 
ERRORCODE_DEKARON_NUM_NOT_ENOUGH : 223, 
//你的奖励已经领取 
ERRORCODE_REWARD_ALREADY_RECV : 224, 
//boss已经死亡 
ERRORCODE_BOSS_ALREADY_DEAD : 225, 
//此用户为黑卡封禁用户 
ERRORCODE_PLAYER_ALREADY_BAN : 226, 
//你已经选择过阵营 
ERRORCODE_CAMP_ALREADY_CHOOSE : 227, 
//推广玩家的等级不够 
ERRORCODE_SEM_USER_LV_NOT_ENOUGH : 228, 
//推广玩家已经达到最大数量 
ERRORCODE_SEM_USER_MAX : 229, 
//推广奖励领取失败 
ERRORCODE_SEM_REWARD_RECV_ERR : 230, 
//你的推广积分不够 
ERRORCODE_SEM_SCORE_NOT_ENOUGH : 231, 
//粮草抢夺时间已经结束了 
ERRORCODE_FORAGE_ROB_TIME_OVER : 232, 
//粮草争夺活动暂未开放 
ERRORCODE_FORAGE_ROB_NOT_OPEN : 233, 
//你没有加入粮草争夺战 
ERRORCODE_FORAGE_ROB_NOT_JOINED : 234, 
//你处于对手匹配的冷却时间中 
ERRORCODE_FIT_MATCH_COOLING : 235, 
//夺粮剩余次数不足 
ERRORCODE_FORAGE_ROB_NUM_NOT_ENOUGH : 236, 
//处于夺粮冷却时间中 
ERRORCODE_FORAGE_ROB_COOLING : 237, 
//对方不在对方列表中 
ERRORCODE_OTHER_SIDE_NOT_IN_LIST : 238, 
//你的复仇次数不足 
ERRORCODE_REVENGE_NUM_NOT_ENOUGH : 239, 
//该仇人并不存在 
ERRORCODE_ENEMY_NOT_EXIST : 240, 
//仇人已复仇 
ERRORCODE_ENEMY_ALREADY_REVENGE : 241, 
//成就ID错误 
ERRORCODE_ACHIEVE_ID_ERR : 242, 
//该成就未达成 
ERRORCODE_ACHIEVE_NOT_REACHED : 243, 
//不可对该玩家就复仇 
ERRORCODE_CAN_NOT_USER_REVENGE : 244, 
//限时优惠商店的商品不足 
ERRORCODE_TIME_LIMIT_SHOP_ITEM_NOT_ENOUGH : 245, 
//限时优惠暂未开始 
ERRORCODE_TIME_LIMIT_DISCOUNT_NOT_OPEN : 246, 
//你已经达到了购买上限 
ERRORCODE_BUY_ITEM_LIMIT : 247, 
//限时优惠商店的全服福利已经领取 
ERRORCODE_DISCOUNT_ALL_SEV_WELFARE_RECV : 248, 
//限时优惠商店全服福利不能领取 
ERRORCODE_DISCOUNT_ALL_SEV_WELFARE_UNABLE : 249, 
//你当前不可领取排行榜奖励 
ERRORCODE_RANK_REWARD_UNABLE_RECV : 250, 
//你的排行榜奖励已经领取 
ERRORCODE_RANK_REWARD_ALREADY_RECV : 251, 
//粮草排行没有任何奖励 
ERRORCODE_FORAGE_RANK_NOT_REWARD : 252, 
//你的粮草令牌已超过购买次数限制 
ERRORCODE_FORAGE_TOKEN_BUY_LIMIT : 253, 
//粮草令牌价格错误 
ERRORCODE_FORAGE_TOKEN_PRICE_ERR : 254, 
//限时优惠商店未找到充值id 
ERRORCODE_TIME_LIMIT_SHOP_ID_ERR : 255, 
//限时优惠商店未找到对应商品 
ERRORCODE_TIME_LIMIT_SHOP_ITEM_ERR : 256, 
//推广非法输入 
ERRORCODE_SEM_INPUT_ILLEGAL : 257, 
//已经注册 
ERRORCODE_ALREADY_REGISTER : 258, 
//正在建立注册关系，请稍等 
ERRORCODE_REGISTRATION : 259, 
//注册失败，新老玩家不在一个跨服上 
ERRORCODE_REGISTER_FAILED_NOT_SAME_SRV : 260, 
//叛军boss刷新请求过于频繁 
ERRORCODE_REBEL_BOSS_REFRESH_FREQUENTLY : 261, 
//叛军boss战斗请求过于频繁 
ERRORCODE_REBEL_BOSS_FIGHT_FREQUENTLY : 262, 
//注册时连跨服失败 
ERRORCODE_REGISTER_CONN_SER_FAILED : 264, 
//军团奖励你已经领取过了，不可重复领取 
ERRORCODE_LEGION_REWARD_ALREADY_RECV : 265, 
//粮草战奖励已领取过 
ERRORCODE_FORAGE_FIGHT_REWARD_ALREADY_RECV : 266, 
//章节奖励已领取过 
ERRORCODE_CHAPTER_REWARD_ALREADY_RECV : 267, 
//军团副本尚未开启 
ERRORCODE_LEGION_RAID_NOT_OPEN : 268, 
//月基金配置错误 
ERRORCODE_MONTH_FUND_CONFIG_ERR : 269, 
//月基金尚未开始 
ERRORCODE_MONTH_FUND_NOT_OPEN : 270, 
//月基金找不到玩家数据 
ERRORCODE_MONTH_FUND_FIND_USER_ERR : 271, 
//月基金不在领取时间 
ERRORCODE_MONTH_FUND_NOT_RECV_TIME : 272, 
//该日奖励已领取 
ERRORCODE_DAILY_REWARD_ALREADY_RECV : 273, 
//没有购买过月基金 
ERRORCODE_NOT_BUY_MONTH_FUND : 274, 
//活动等级不匹配 
ERRORCODE_ACTIVITY_LV_NOT_MATCH : 275, 
//活动VIP等级不匹配 
ERRORCODE_ACTIVITY_VIPLV_NOT_MATCH : 276, 
//38级开启向陌生人发送邮件 
ERRORCODE_LV38_SEND_MAIL_TO_STRANGER : 277, 
//每日对陌生人发送邮件数量不能超过10封 
ERRORCODE_SEND_MAIL_TO_STRANGER_LIMIT : 278, 
//新手光环活动已结束 
ERRORCODE_NOVICE_HALO_ACTIVITY_FINISH : 279, 
//限时抽将的阵营已变 
ERRORCODE_LIMIT_TIME_LOTTERY_HERO_CHANGE : 280, 
//限时抽将的次数不足 
ERRORCODE_LIMIT_TIME_LOTTERY_HERO_LIMIT : 281, 
//限时抽将的主体将不符合 
ERRORCODE_LIMIT_TIME_LOTTERY_MAIN_HERO : 282, 
//您的星运值不足 
ERRORCODE_STAR_LUCK_NOT_ENOUGH : 283, 
//您的购买次数不足 
ERRORCODE_BUY_COUNT_NOT_ENOUGH : 284, 
//你的团购领奖出现异常 
ERRORCODE_GROUPON_RECV_REWARD_EXCEPTION : 285, 
//您的领奖积分不足 
ERRORCODE_REWARD_SCORE_NOT_ENOUGH : 286, 
//您的全服领奖积分不足 
ERRORCODE_ALL_SRV_REWARD_SCORE_NOT_ENOUGH : 287, 
//你的团购奖励已经领取过了 
ERRORCODE_GROUPON_REWARD_ALREADY_RECV : 288, 
//你限时团购返还的元宝出现异常 
ERRORCODE_GROUPON_REBATE_YUANBAO_EXCEPTION : 289, 
//您团购的vip等级不足 
ERRORCODE_GROUPON_VIPLV_NOT_ENOUGH : 290, 
//你的团购等级出现异常 
ERRORCODE_GROUPON_LV_EXCEPTION : 291, 
//限时团购当前不能购买 
ERRORCODE_LIMIT_TIME_GROUPON_UNABLE_BUY : 292, 
//限时团购玩家数据异常 
ERRORCODE_LIMIT_TIME_GROUPON_EXCEPTION : 293, 
//该活动不在活动时间 
ERRORCODE_ACTIVITY_TIME_EXPIRE : 294, 
//团购不在领奖时间 
ERRORCODE_GROUPON_NOT_IN_RECV_TIME : 295, 
//团购玩家数据异常 
ERRORCODE_GROUPON_USER_DATA_EXCEPTION : 296, 
//更换头像框发生异常 
ERRORCODE_REPLACE_HEAD_ICON_EXCEPTION : 297, 
//战宠背包已满 
ERRORCODE_BATTLE_PET_BAG_FULL : 298, 
//不存在本战宠 
ERRORCODE_BATTLE_PET_NOT_EXIST : 299, 
//该宠物已上阵 
ERRORCODE_BATTLE_PET_ALREADY_PLAY : 300, 
//未满足进入下一关的条件 
ERRORCODE_NEXT_PASS_COND_NOT_MEET : 301, 
//无法重置百战沙场 
ERRORCODE_UNABLE_RESET_BATTLEFIELD : 302, 
//百战沙场信息过期 
ERRORCODE_BATTLEFIELD_INFO_EXPIRE : 303, 
//军库秘藏领奖失败 
ERRORCODE_RECV_ARSENALS_REWARD_FAILED : 304, 
//本关卡已被击败 
ERRORCODE_RAID_ALREADY_BEAT : 305, 
//正在加载，请稍等 
ERRORCODE_LOADING : 306, 
//战宠商店刷新次数不足 
ERRORCODE_PET_SHOP_REFRESH_LIMIT : 307, 
//当前章节过低，无法领取宝藏 
ERRORCODE_CHAPTER_LOW_UNABLE_RECV_REWARD : 308, 
//兽魂不足够 
ERRORCODE_BEAST_SOUL_NOT_ENOUGH : 309, 
//灵玉不足够 
ERRORCODE_JADE_NOT_ENOUGH : 310, 
//军团贡献不足够 
ERRORCODE_DEVOTE_NOT_ENOUGH : 311, 
//虎牢积分不足够 
ERRORCODE_SCORE_NOT_ENOUGH : 312, 
//碎片不足够 
ERRORCODE_CHIP_NUM : 313, 
//爬塔失败，需要重置才能继续爬塔 
ERRORCODE_TOWER_NEED_RESET : 314, 
//叛军副本未开始 
ERRORCODE_REBEL_NOT_OPEN : 315, 
//叛军已经跳跑 
ERRORCODE_REBEL_JUMPED_WAY : 316, 
//吃黄瓜奖励已领取 
ERRORCODE_ALREADY_EAT_CUCUMBER : 317, 
//未到吃黄瓜时间 
ERRORCODE_NOT_EAT_CUCUMBER_TS : 318, 
//奖励已经领取完[7日日常任务(物品限量)] 
ERRORCODE_REWARD_ALREADY_RECEIVE_END : 319, 
//不允许卖出 
ERRORCODE_NOT_ALLOWED_SELL : 320, 
//点赞次数消耗完 
ERRORCODE_AVAILABLE_TIMES_DEPLETE : 321, 
//跨服军团状态错误 
ERRORCODE_SPAN_SRV_LEGION_STATE_ERR : 1000, 
//跨服军团已经报名 
ERRORCODE_SPAN_SRV_LEGION_ALREADY_REGISTER : 1001, 
//此跨服军团未报名 
ERRORCODE_SPAN_SRV_LEGION_NOT_REGISTER : 1002, 
//跨服军团报名条件不满足 
ERRORCODE_SPAN_SRV_LEGION_REG_COND_ERR : 1004, 
//跨服战鼓舞次数已超过军团最大次数 
ERRORCODE_SPAN_SRV_INSPIRE_LEGION_LIMIT : 1005, 
//跨服鼓舞超过玩家最大次数 
ERRORCODE_SPAN_SRV_INSPIRE_USER_LIMIT : 1006, 
//跨服战斗刷新CD中 
ERRORCODE_SPAN_SRV_FIGHT_REFRESH_COOLING : 1007, 
//跨服战斗CD中 
ERRORCODE_SPAN_SRV_FIGHT_COOLING : 1008, 
//不在跨服战斗CD中 
ERRORCODE_SPAN_SRV_FIGHT_NOT_COOLING : 1009, 
//该战场不存在 
ERRORCODE_BATTLEFIELD_NOT_EXIST : 1010, 
//查询异常 
ERRORCODE_QUERY_EXCEPTION : 1011, 
//军团挑战玩家达到最大次数 
ERRORCODE_LEGION_DEKARON_USER_LIMIT : 1013, 
//不能设置自己为集火目标 
ERRORCODE_UNABLE_SET_SELF_TARGET : 1014, 
//军团战状态锁定中 
ERRORCODE_LEGION_STATE_IS_LOCKING : 1015, 
//跨服服务器忙 
ERRORCODE_SPAN_SRV_BUSY : 1016, 
//跨服演武重置次数达到上限 
ERRORCODE_SPAN_SRV_ENBU_RESET_LIMIT : 1017, 
//比武服务器战场信息发生错误 
ERRORCODE_JOUST_SRV_BATTLEFIELD_ERR : 1018, 
//比武状态发生错误 
ERRORCODE_JOUST_STATE_ERR : 1019, 
//比武的玩家未选择阵营 
ERRORCODE_JOUST_USER_NOT_CHOSE_CAMP : 1020, 
//你已经没有任何刷新次数 
ERRORCODE_REFRESH_COUNT_EXHAUSTION : 1021, 
//比武玩家请求列表过于频繁 
ERRORCODE_JOUST_USER_LIST_FREQUENTLY : 1022, 
//请求战斗中发生错误 
ERRORCODE_FIGHT_ERR : 1023, 
//您已经挑战过了 
ERRORCODE_ALREADY_DEKARON : 1024, 
//你已经没有任何挑战次数 
ERRORCODE_DEKARON_COUNT_FREQUENTLY : 1025, 
//获取对手信息失败 
ERRORCODE_GET_PEER_INFO_FAILED : 1026, 
//你未获得争霸赛的邀请资格 
ERRORCODE_COMPETITION_PERMISSION_DENIED : 1027, 
//投注错误 
ERRORCODE_BETTING_ERR : 1028, 
//已经领取过全服奖励 
ERRORCODE_ALL_REWARD_ALREADY_RECV : 1029, 
//奖励处于初始化状态 
ERRORCODE_REWARD_INIT_STATE : 1030, 
//你未达成奖励条件 
ERRORCODE_REWARD_COND_NOT_MEET : 1031, 
//争霸赛尚未开启 
ERRORCODE_COMPETITION_NOT_OPEN : 1032, 
//投注处于初始化状态 
ERRORCODE_BETTING_INIT_STATE : 1033, 
//投注处于结算状态 
ERRORCODE_BETTING_ACCOUNT_STATE : 1034, 
//挑战信息错误 
ERRORCODE_DEKARON_INFO_ERR : 1035, 
//该玩家正在被挑战 
ERRORCODE_USER_IS_DEKARON : 1036, 
//投注已经超过上限 
ERRORCODE_BETTING_LIMIT : 1037, 
//你已经领取过投注奖励 
ERRORCODE_BETTING_REWARD_ALREADY_RECV : 1038, 
//玩家信息获取失败 
ERRORCODE_GET_PLAYER_INFO_FAILED : 1039, 
//您今天已经签到过了 
ERRORCODE_REPEAT_SIGN : 1040, 
//您没有可补签的天数了 
ERRORCODE_NO_NEED_SPEND_SIGN : 1041, 
//您没有可领取的累计签到奖励了 
ERRORCODE_HAVE_NO_SIGN_REWARD : 1042, 
//累计签到天数未达到要求 
ERRORCODE_LESS_SIGN_DAYS : 1043, 
//请先对今天进行签到 
ERRORCODE_MUST_SIGN_TODAY : 1044, 
//摇钱树还在冷却中 
ERRORCODE_MONEY_TREE_CD : 1045, 
//摇钱树所有奖励已经领取完了 
ERRORCODE_MONEY_TREE_DONE : 1046, 
//强化或精炼过的宝物不可以当作材料 
ERRORCODE_INVALID_TREASURE_MATERIAL : 1047, 
//大黄庭已经满级了 
ERRORCODE_DAHUANGTING_LEVEL_MAX : 1048, 
//你挑战次数已用完 
ERRORCODE_ELITE_TOWER_COUNT_LIMIT : 1049, 
//叛军已经死亡 
ERRORCODE_REBEL_IS_DEAD : 1050, 
//该叛军已经不存在了 
ERRORCODE_REBEL_NOT_EXIST : 1051, 
//金将不能被分解 
ERRORCODE_GOLD_CARD_DENY_FENJIE : 1052, 
//您今日购买精英挑战次数已达上限 
ERRORCODE_TOWER_ELITE_BUY_LIMIT : 1053, 
//您今日挑战雪刀传次数已达上限 
ERRORCODE_FAMOUS_RAID_LIMIT : 1054, 
//今日重置次数已用尽 
ERRORCODE_TOWER_RESET_LIMIT : 1055, 
//您需要提升VIP等级才能使用该功能 
ERRORCODE_FUNC_NEED_VIP_LEVEL : 1056, 
//您今日重置该副本次数已达上限 
ERRORCODE_RAID_RESET_LIMIT : 1057, 
//玩家已在军团中 
ERRORCODE_ROLE_IN_LEGION : 1058, 
//玩家没有军团 
ERRORCODE_ROLE_NOT_IN_LEGION : 1059, 
//LOGO非法 
ERRORCODE_LEGION_LOGO_INVALID : 1060, 
//玩家不是军团长 
ERRORCODE_NOT_LEGION_HEAD : 1061, 
//军团成员过多 
ERRORCODE_LEGION_MEMBER_NUM_LIMIT : 1062, 
//您今日刷新次数已达上限 
ERRORCODE_SHOP_REFRESH_LIMIT : 1063, 
//VIP积分不足 
ERRORCODE_VIP_SCORE_NOT_ENOUGH : 1064, 
//玩家没申请该军团 
ERRORCODE_LEGION_NOT_APPLIED : 1065, 
//您今日取悦次数已用完 
ERRORCODE_BLUSHER_WOO_LIMIT : 1066, 
//只能踢出下级 
ERRORCODE_CAN_ONLY_DEL_SUBORDINATE : 1067, 
//对方已不在军团 
ERRORCODE_OTHER_NOT_IN_LEGION : 1068, 
//副团长已满 
ERRORCODE_LEGION_DEPUTY_FULL : 1069, 
//对方不是副团长 
ERRORCODE_OTHER_NOT_LEGION_DEPUTY : 1070, 
//VIP等级不匹配 
ERRORCODE_VIP_LEVEL_MISMATCH : 1071, 
//您今天已经领取过了该福利 
ERRORCODE_REPEAT_DRAW_VIP_WELFARE : 1072, 
//商城数据已过期 
ERRORCODE_LEGION_LIMIT_SHOP_INFO_EXPIRED : 1073, 
//该商品已经售完 
ERRORCODE_LEGION_LIMIT_SHOP_SOLD_OUT : 1074, 
//帮派祭天次数已达最大值 
ERRORCODE_LEGION_WORSHIP_COUNT_LIMIT : 1075, 
//今天已祭天 
ERRORCODE_LEGION_WORSHIP_DONE : 1076, 
//该祭天宝箱已领取 
ERRORCODE_LEGION_WORSHIP_BOX_OPENED : 1077, 
//创建帮派的vip等级不足 
ERRORCODE_CREATE_LEGION_VIP_LEVEL_LIMIT : 1078, 
//祭天的vip等级不足 
ERRORCODE_LEGION_WORSHIP_VIP_LEVEL_LIMIT : 1079, 
//该帮派技能等级已达到学习上限 
ERRORCODE_LEGION_SKILL_LEARN_LIMIT : 1080, 
//该帮派技能等级已达到研究上限 
ERRORCODE_LEGION_SKILL_RESEARCH_LIMIT : 1081, 
//帮派经验不足 
ERRORCODE_LEGION_EXP_NOT_ENOUGH : 1082, 
//帮派等级不足 
ERRORCODE_LEGION_LEVEL_LIMIT : 1083, 
//兑换已达到上限 
ERRORCODE_EXCHANGE_COUNT_LIMIT : 1084, 
//该留言信息不存在 
ERRORCODE_LEGION_MESSAGE_NOT_EXIST : 1085, 
//该留言信息已置顶 
ERRORCODE_LEGION_MESSAGE_ALREADY_STICKY : 1086, 
//该留言信息没置顶 
ERRORCODE_LEGION_MESSAGE_NOT_STICKY : 1087, 
//10分钟只能留言一次 
ERRORCODE_LEGION_MESSAGE_INTERVAL_LIMIT : 1088, 
//帮主离线时间不满7天 
ERRORCODE_LEGION_HEAD_OFFLINE_LIMIT : 1089, 
//已经有人弹劾帮主 
ERRORCODE_LEGION_IMPEACH_ALREADY_BEGIN : 1090, 
//已经到最高层了 
ERRORCODE_TOWER_LADDER_SWEEP_MAX : 1091, 
//离开帮派后要24小时之后才能重新建帮或入帮 
ERRORCODE_LEGION_OUT_TIME_LIMIT : 1092, 
//该成员入帮不足24小时，不能踢出 
ERRORCODE_LEGION_IN_TIME_LIMIT : 1093, 
//侠客达到50级才能觉醒 
ERRORCODE_AWAKEN_LEVEL_NOT_ENGOUGH : 1094, 
//体力达到500上限 
ERRORCODE_EXCEED_POWER_LIMIT : 1095, 
//精力达到200上限 
ERRORCODE_EXCEED_ENERGY_LIMIT : 1096, 
//已上阵武将不能分解或重生 
ERRORCODE_HERO_IS_NOT_IDLE : 1097, 
//已穿戴的装备不能分解或重生 
ERRORCODE_EQUIP_IS_NOT_IDLE : 1098, 
//已穿戴的宝物不能分解或重生 
ERRORCODE_TREASURE_IS_NOT_IDLE : 1099, 
//服务器正在维护中 
ERRORCODE_SERVER_IN_MAINTENANCE : 1100, 
//寻访战力不足 
ERRORCODE_VISIT_POWER_NOT_ENOUGH : 1101, 
//寻访等级不足 
ERRORCODE_VISIT_LEVEL_NOT_ENOUGH : 1102, 
//道具不足 
ERRORCODE_TERRITORY_ITEM_NOT_ENOUGH : 1103, 
//使用道具数量达到上限 
ERRORCODE_TERRITORY_USE_ITEM_LIMIT : 1104, 
//今日的免费刷新次数已达上限 
ERRORCODE_TERRITORY_FREE_REFRESH_LIMIT : 1105, 
//今日的挑战次数已用完 
ERRORCODE_TERRITORY_FIGHT_CNT_LIMIT : 1106, 
//当前没有玩家开启寻访 
ERRORCODE_NO_VISIT_ROUTE_EXIST : 1107, 
//直接攻下了据点 
ERRORCODE_FORTRESS_DIRECT_WIN : 1108, 
//据点已经丢失 
ERRORCODE_FORTRESS_HAS_BEEN_LOST : 1109, 
//据点正在保护期 
ERRORCODE_FORTRESS_IN_PROTECTION : 1110, 
//未达到领取条件 
ERRORCODE_FORTRESS_CAN_NOT_DRAW_BOX : 1111, 
//该奖励已经领取过了 
ERRORCODE_FORTRESS_REPEAT_DRAW_BOX : 1112, 
//没有能快马加鞭的寻访路线 
ERRORCODE_VISIT_NO_ROUTE_CAN_SPEEDUP : 1113, 
//不能对该寻访路线快马加鞭 
ERRORCODE_VISIT_ROUTE_CANNOT_SPEEDUP : 1114, 
//现在是停战期，不能挑战 
ERRORCODE_FORTRESS_STOP_FIGHT : 1115, 
//已达当天最大领取钱袋数 
ERRORCODE_VISIT_REWARD_COUNT_LIMIT : 1116, 
//没有可领取奖励的路线 
ERRORCODE_NO_VISIT_ROUTE_REWARD : 1117, 
//未到开启时间 
ERRORCODE_TERRITORY_NOT_OPEN : 1118, 
//已购买开服基金 
ERRORCODE_ALREADY_BUY_OPEN_FUND : 1119, 
//未购买开服基金 
ERRORCODE_HAS_NOT_BUY_OPEN_FUND : 1120, 
//该开服基金奖励已领取 
ERRORCODE_HAS_GET_OPEN_FUND : 1121, 
//未达到指定等级 
ERRORCODE_OPEN_FUND_LEVEL_LIMIT : 1122, 
//该全民福利已领取 
ERRORCODE_HAS_GET_WELFARE : 1123, 
//购买开服基金人数未达到指定数量 
ERRORCODE_WELFARE_BUY_NUM_LIMIT : 1124, 
//请求的商品不存在 
ERRORCODE_NO_MATCHING_PRODUCT : 1125, 
//商品数量错误 
ERRORCODE_PRODUCT_NUM_WRONG : 1126, 
//永久卡不能重复购买 
ERRORCODE_MONTH_CARD_CANNOT_REPEAT : 1127, 
//未到月卡可购买时间 
ERRORCODE_MONTH_CARD_TIME_LIMIT : 1128, 
//月卡奖励一天只能领取一次 
ERRORCODE_SAME_DAY_GET_TWICE : 1129, 
//月卡已过期 
ERRORCODE_MONTH_CARD_DEADLINE : 1130, 
//还未到武帝挑战时间 
ERRORCODE_NOT_WUDI_FIGHT_TIME : 1131, 
//武帝已经被击败了 
ERRORCODE_WUDI_HAS_DIED : 1132, 
//你已经没有挑战次数了 
ERRORCODE_WUDI_FIGHT_CNT_LIMIT : 1133, 
//挑战冷却时间未到 
ERRORCODE_WUDI_FIGHT_CD_LIMIT : 1134, 
//购买挑战次数已达到上限了 
ERRORCODE_WUDI_FIGHT_BUY_CNT_LIMIT : 1135, 
//没达到该帮派要求的贵族等级 
ERRORCODE_LEGION_APPLY_VIP_LIMIT : 1136, 
//没达到该帮派要求的等级 
ERRORCODE_LEGION_APPLY_LV_LIMIT : 1137, 
//没达到该帮派要求的战力 
ERRORCODE_LEGION_APPLY_FIGHT_LIMIT : 1138, 
//已获得首充奖励 
ERRORCODE_FIRST_RECHARGE_AWARD_ALREADY_GET : 1139, 
//已购买同类型月卡 
ERRORCODE_MONTH_CARD_SAME_TYPE : 1140, 
//没有帮派副本挑战次数 
ERRORCODE_LEGION_BOSS_NO_COUNT : 1141, 
//帮派副本挑战冷却中 
ERRORCODE_LEGION_BOSS_IN_CD : 1142, 
//不在帮派副本挑战规定时间 
ERRORCODE_LEGION_BOSS_TIME_INVALID : 1143, 
//帮派等级过低，未达开启帮派副本开启要求 
ERRORCODE_LEGION_BOSS_LEVEL_LIMIT : 1144, 
//该奖励已领取 
ERRORCODE_LEGION_BOSS_REWARD_GOT : 1145, 
//该关副本未开启 
ERRORCODE_LEGION_BOSS_NOT_OPEN : 1146, 
//该关副本已通关 
ERRORCODE_LEGION_BOSS_KILLED : 1147, 
//你今日的充值金额不足 
ERRORCODE_LUXURY_SIGN_RECHARGE_NOT_ENOUGH : 1148, 
//该奖励已领取 
ERRORCODE_LUXURY_SIGN_ALREADY_GET : 1149, 
//该帮派你已申请，请耐心等待帮主审核 
ERRORCODE_LEGION_ALREADY_APPLIED : 1150, 
//今日领取精力次数已用完 
ERRORCODE_RECV_FRIEND_ENERGY_LIMIT : 1151, 
//无效的新名字 
ERRORCODE_INVALID_RENAME : 1152, 
//您的账号存在异常，具体请联系客服。 
ERRORCODE_USER_BANED : 1153, 
//该据点未参与武帝预选，暂不能挑战 
ERRORCODE_NOT_TAKEPARTIN_WUDI : 1154, 
//已向好友分享过该叛军 
ERRORCODE_REPEAT_SHARE_REBEL : 1155, 
//该招贤活动已过期 
ERRORCODE_CHOUKA_HAS_EXPIRED : 1156, 
//在对方黑名单中，不能加为好友 
ERRORCODE_IN_PEER_BLACKLIST : 1157, 
//你未达到装备该时装所要求的等级 
ERRORCODE_FASHION_DRESS_LV_LIMIT : 1158, 
//您的幸运值不足 
ERRORCODE_ZHAOHUAN_LUCK_NOT_ENOUGH : 1159, 
//时装数量不足 
ERRORCODE_FASHION_NUM_NOT_ENOUGH : 1160, 
//该活动已结束 
ERRORCODE_TURNTABLE_ENDED : 1161, 
//抽奖失败，需要刷后再试 
ERRORCODE_TURNTABLE_REWARD_FAIL : 1162, 
//该任务已经不存在了 
ERRORCODE_TASK_NOT_EXIST : 1163, 
//该任务还未完成 
ERRORCODE_TASK_UNCOMLETED : 1164, 
//该活动已结束 
ERRORCODE_ZHAOCAIMAO_ENDED : 1165, 
//所有奖已抽完 
ERRORCODE_ZHAOCAIMAO_NO_MORE : 1166, 
//该任务已达到次数限制 
ERRORCODE_TASK_COUNT_LIMIT : 1167, 
//本赛季已结束 
ERRORCODE_CS_POINTS_RACE_ENDED : 1168, 
//侠义不足够 
ERRORCODE_XIAYI_NOT_ENOUGH : 1169, 
//阅历不足够 
ERRORCODE_YUELI_NOT_ENOUGH : 1170, 
//该豪侠不能分解 
ERRORCODE_GALLANT_CANNOT_FENJIE : 1171, 
//该豪侠不能直接合成 
ERRORCODE_GALLANT_CANNOT_COMPOSE : 1172, 
//您已经打败了对方，不能重复挑战 
ERRORCODE_CS_POINTS_HAS_DIED : 1173, 
//获取对方数据异常 
ERRORCODE_CS_POINTS_OPPONENT_ERROR : 1174, 
//该条目已激活 
ERRORCODE_GALLANT_ENTRY_ALREADY_ACTIVATE : 1175, 
//跨服积分赛挑战次数不足 
ERRORCODE_CSPOINTSRACE_CNT_NOT_ENOUGH : 1176, 
//跨服积分赛荣誉点数不足 
ERRORCODE_CSPOINTSRACE_HONOR_NOT_ENOUGH : 1177, 
//跨服积分赛挑战次数已达上限 
ERRORCODE_CSPOINTSRACE_CNT_MAX_LIMIT : 1178, 
//跨服争霸赛未开启 
ERRORCODE_CS_POINTS_RACE_NOT_OPEN : 1179, 
//您已复仇对方，不能重复复仇 
ERRORCODE_CS_POINTS_RACE_HASREVENGED : 1180, 
//侠义商店已刷新 
ERRORCODE_HAOXIA_SHOP_ALREADY_REFRESH : 1181, 
//该商品已经过期了 
ERRORCODE_LIMITED_TIME_BUY_EXPIRED : 1182, 
//不能重复购买该商品 
ERRORCODE_LIMITED_TIME_BUY_REPEAT : 1183, 
//返利已在它服领取 
ERRORCODE_GET_REBATE_ERROR : 1184, 
//已过返利领取的截止时间 
ERRORCODE_GET_REBATE_DEADLINE : 1185, 
//该服务器已满，请重新选择其它服务器 
ERRORCODE_ERRORCODE_SERVER_IS_FULL : 1186, 
//您的VIP等级不够 
ERRORCODE_ERRORCODE_VIPLV_NOT_ENOUGH : 1187, 
//战宠等级不能超过主角等级 
ERRORCODE_PET_LV_LIMIT : 1188, 
//世界频道聊天需玩家等级达到20级 
ERRORCODE_CHAT_LV_LIMIT : 1189, 
//世界频道聊天需玩家买月卡 
ERRORCODE_CHAT_MONTH_CARD_LIMIT : 1190, 
//跨服服务器正在维护中 
ERRORCODE_CROSSSERVER_IN_MAINTAIN : 1191, 
//年兽活动尚未开启 
ERRORCODE_NIAN_EVENT_NOT_BEGIN : 1192, 
//年兽活动已结束 
ERRORCODE_NIAN_EVENT_END : 1193, 
//年兽已被击杀 
ERRORCODE_NIAN_DEAD : 1194, 
//年兽红包进度未达到 
ERRORCODE_NIAN_PROGRESS_NOT_REACH : 1195, 
//年兽红包已领取 
ERRORCODE_NIAN_RED_PACKET_ALREADY_GET : 1196, 
//年兽礼花不能购买 
ERRORCODE_NIAN_FIREWORKS_CANT_BUY : 1197, 
//成就未完成 
ERRORCODE_ACHIEVEMENT_TASK_NOT_COMPLETE : 1198, 
//成就奖励已领 
ERRORCODE_ACHIEVEMENT_REWARD_HAVE_GOT : 1199, 
//挑战次数已用完 
ERRORCODE_NO_PET_RAID_FIGHT_COUNT : 1200, 
//该关卡不能挑战 
ERRORCODE_PET_RAID_CANNOT_FIGHT : 1201, 
//已是宠物副本最后一关 
ERRORCODE_PET_RAID_LAST_ID : 1202, 
//已到宠物副本历史最高关 
ERRORCODE_PET_RAID_IS_MAX_COUNT : 1203, 
//一键通关只能用一次 
ERRORCODE_PET_RAID_ALREADY_USE_ONE_KEY : 1204, 
};
exports = module.exports = DEF_ErrorCode;