public class MonsterTable
{
	 public int id;
	 public string name;
	 public int bossid;
	 public int image_id;
	 public int skill_audio_id;
	 public int dead_audio_id;
	 public int play_group_id;
	 public int quality;
	 public int attack_type;
	 public int hp;
	 public int attack;
	 public int magicAttack;
	 public int defense;
	 public int magic_defense;
	 public int hit;
	 public int dodge;
	 public int crit;
	 public int kang_bao;
	 public int add_hurt;
	 public int dec_hurt;
	 public int anger;
	 public int anger_reset;
	 public int attack_id;
	 public int skill_id;
	 public int total_skill_id;
	 public int immune_dec_anger;
	 public int immune_vertigo;
}
