public class SanguoZhiTable
{
	 public int id;
	 public string name;
	 public int desc_type;
	 public string desc;
	 public int page;
	 public string icon;
	 public string layout;
	 public int prepose_id;
	 public int cost_num;
	 public int function_type;
	 public int attribute_type;
	 public int attribute_value;
	 public int reward_type;
	 public int type_1;
	 public int value_1;
	 public int size_1;
	 public int type_2;
	 public int value_2;
	 public int size_2;
	 public int type_3;
	 public int value_3;
	 public int size_3;
	 public int type_4;
	 public int value_4;
	 public int size_4;
	 public string image_off;
	 public string image_on;
	 public string text_off;
	 public string text_on;
}
