public class SlotMachineTaskTable
{
	 public int id;
	 public string task_desc;
	 public int min_level;
	 public int max_level;
	 public int task_type;
	 public int task_num;
	 public int jump_type;
	 public int condition_type;
	 public int condition_value_1;
	 public int condition_value_2;
	 public int item_type_1;
	 public int item_value_1;
	 public int item_num_1;
	 public int item_type_2;
	 public int item_value_2;
	 public int item_num_2;
	 public int item_type_3;
	 public int item_value_3;
	 public int item_num_3;
	 public int item_type_4;
	 public int item_value_4;
	 public int item_num_4;
	 public int progress;
	 public int exchange_type;
	 public int exchange_id;
	 public int exchange_num;
	 public string tag;
	 public int in_use;
}
