public class VisitStationTable
{
	 public int id;
	 public string name;
	 public int time;
	 public int speed_up;
	 public int speed_up_limit;
	 public int reward_type1;
	 public int low_reward_value1;
	 public int mid_reward_value1;
	 public int high_reward_value1;
	 public string desc1;
	 public int reward_type2;
	 public int low_reward_value2;
	 public int mid_reward_value2;
	 public int high_reward_value2;
	 public string desc2;
	 public int low_consume_type1;
	 public int low_consume_value1;
	 public int low_consume_type2;
	 public int low_consume_value2;
	 public int mid_consume_type1;
	 public int mid_consume_value1;
	 public int mid_consume_type2;
	 public int mid_consume_value2;
	 public int high_consume_type1;
	 public int high_consume_value1;
	 public int high_consume_type2;
	 public int high_consume_value2;
	 public int event_group;
}
