--帮派属性 
module('DEF_LegionAttr')
--等级 
LEGION_ATTR_LEVEL = 1 
--经验 
LEGION_ATTR_EXP = 2 
--当前成员数量 
LEGION_ATTR_MEMBER_NUMBER = 3 
--祭天进度 
LEGION_ATTR_WORSHIP_VALUE = 4 
--标志ID 
LEGION_ATTR_LOGO_ID = 5 
--边框ID 
LEGION_ATTR_FRAME_ID = 6 
--祭天人数 
LEGION_ATTR_WORSHIP_COUNT = 7 
--最大帮派属性 
LEGION_ATTR_MAX = 8 