//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuyWudiFightCntRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyWudiFightCntRequest")]
  public partial class BuyWudiFightCntRequest : global::ProtoBuf.IExtensible
  {
    public BuyWudiFightCntRequest() {}
    
    private uint _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint _boss_ts;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"boss_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint boss_ts
    {
      get { return _boss_ts; }
      set { _boss_ts = value; }
    }
    private uint _buy_cnt;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"buy_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buy_cnt
    {
      get { return _buy_cnt; }
      set { _buy_cnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}