//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CommonRankLikeAnswer.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonRankLikeAnswer")]
  public partial class CommonRankLikeAnswer : global::ProtoBuf.IExtensible
  {
    public CommonRankLikeAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private U64Type _like_player_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"like_player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type like_player_id
    {
      get { return _like_player_id; }
      set { _like_player_id = value; }
    }
    private uint _likes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"likes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint likes
    {
      get { return _likes; }
      set { _likes = value; }
    }
    private uint _left_like_count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"left_like_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_like_count
    {
      get { return _left_like_count; }
      set { _left_like_count = value; }
    }
    private uint _silver;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"silver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint silver
    {
      get { return _silver; }
      set { _silver = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}