//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CrusadeFortressInfoAnswer.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CrusadeFortressInfoAnswer")]
  public partial class CrusadeFortressInfoAnswer : global::ProtoBuf.IExtensible
  {
    public CrusadeFortressInfoAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _kill_count;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"kill_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint kill_count
    {
      get { return _kill_count; }
      set { _kill_count = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _reward_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"reward_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_ids
    {
      get { return _reward_ids; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _reward_types = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(12, Name=@"reward_types", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_types
    {
      get { return _reward_types; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _reward_nums = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"reward_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_nums
    {
      get { return _reward_nums; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _box_states = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(14, Name=@"box_states", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> box_states
    {
      get { return _box_states; }
    }
  
    private U64Type _cur_hp;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"cur_hp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type cur_hp
    {
      get { return _cur_hp; }
      set { _cur_hp = value; }
    }
    private U64Type _hp_limit;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"hp_limit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type hp_limit
    {
      get { return _hp_limit; }
      set { _hp_limit = value; }
    }
    private uint _today_occupide_time;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"today_occupide_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint today_occupide_time
    {
      get { return _today_occupide_time; }
      set { _today_occupide_time = value; }
    }
    private uint _protect_cd;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"protect_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint protect_cd
    {
      get { return _protect_cd; }
      set { _protect_cd = value; }
    }
    private uint _buy_cnt;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"buy_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buy_cnt
    {
      get { return _buy_cnt; }
      set { _buy_cnt = value; }
    }
    private U64Type _player_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private uint _occupide_level;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"occupide_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint occupide_level
    {
      get { return _occupide_level; }
      set { _occupide_level = value; }
    }
    private uint _fight_cnt;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"fight_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_cnt
    {
      get { return _fight_cnt; }
      set { _fight_cnt = value; }
    }
    private uint _total_buy_fight_cnt;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"total_buy_fight_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint total_buy_fight_cnt
    {
      get { return _total_buy_fight_cnt; }
      set { _total_buy_fight_cnt = value; }
    }
    private uint _my_fortress_id;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"my_fortress_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_fortress_id
    {
      get { return _my_fortress_id; }
      set { _my_fortress_id = value; }
    }

    private uint _reason = default(uint);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }

    private uint _fashion_id = default(uint);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }
    private uint _card_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint card_id
    {
      get { return _card_id; }
      set { _card_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _fight_cap;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fight_cap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_cap
    {
      get { return _fight_cap; }
      set { _fight_cap = value; }
    }
    private uint _total_occupide_time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"total_occupide_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint total_occupide_time
    {
      get { return _total_occupide_time; }
      set { _total_occupide_time = value; }
    }
    private uint _income_cd;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"income_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint income_cd
    {
      get { return _income_cd; }
      set { _income_cd = value; }
    }
    private uint _defense_count;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"defense_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint defense_count
    {
      get { return _defense_count; }
      set { _defense_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}