//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CrusadeFortressBaseInfo.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CrusadeFortressBaseInfo")]
  public partial class CrusadeFortressBaseInfo : global::ProtoBuf.IExtensible
  {
    public CrusadeFortressBaseInfo() {}
    
    private U64Type _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private uint _fashion_id = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }
    private uint _card_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint card_id
    {
      get { return _card_id; }
      set { _card_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _fight_cap;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fight_cap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_cap
    {
      get { return _fight_cap; }
      set { _fight_cap = value; }
    }
    private U64Type _cur_hp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"cur_hp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type cur_hp
    {
      get { return _cur_hp; }
      set { _cur_hp = value; }
    }
    private U64Type _hp_limit;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"hp_limit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type hp_limit
    {
      get { return _hp_limit; }
      set { _hp_limit = value; }
    }
    private uint _protect_cd;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"protect_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint protect_cd
    {
      get { return _protect_cd; }
      set { _protect_cd = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}