//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CrusadeFortressAllInfoAnswer.proto
// Note: requires additional types generated from: CrusadeFortressBaseInfo.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CrusadeFortressAllInfoAnswer")]
  public partial class CrusadeFortressAllInfoAnswer : global::ProtoBuf.IExtensible
  {
    public CrusadeFortressAllInfoAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<CrusadeFortressBaseInfo> _baseInfo = new global::System.Collections.Generic.List<CrusadeFortressBaseInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"baseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CrusadeFortressBaseInfo> baseInfo
    {
      get { return _baseInfo; }
    }
  

    private uint _fight_cnt = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fight_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight_cnt
    {
      get { return _fight_cnt; }
      set { _fight_cnt = value; }
    }

    private uint _total_buy_fight_cnt = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"total_buy_fight_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_buy_fight_cnt
    {
      get { return _total_buy_fight_cnt; }
      set { _total_buy_fight_cnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}