//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CSPointsRaceGetOpponentsAnswer.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPointsRaceGetOpponentsAnswer")]
  public partial class CSPointsRaceGetOpponentsAnswer : global::ProtoBuf.IExtensible
  {
    public CSPointsRaceGetOpponentsAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _level = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> level
    {
      get { return _level; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _points = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> points
    {
      get { return _points; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _rank = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(12, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> rank
    {
      get { return _rank; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _is_win = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"is_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> is_win
    {
      get { return _is_win; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _role_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(14, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> role_id
    {
      get { return _role_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _fashion_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(15, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> fashion_id
    {
      get { return _fashion_id; }
    }
  

    private uint _my_rank = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"my_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint my_rank
    {
      get { return _my_rank; }
      set { _my_rank = value; }
    }
    private uint _refresh_cd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"refresh_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint refresh_cd
    {
      get { return _refresh_cd; }
      set { _refresh_cd = value; }
    }
    private uint _my_points;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"my_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_points
    {
      get { return _my_points; }
      set { _my_points = value; }
    }
    private uint _my_continuous_wins;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"my_continuous_wins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_continuous_wins
    {
      get { return _my_continuous_wins; }
      set { _my_continuous_wins = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _index = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> index
    {
      get { return _index; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _server_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> server_id
    {
      get { return _server_id; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _server_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"server_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> server_name
    {
      get { return _server_name; }
    }
  
    private readonly global::System.Collections.Generic.List<U64Type> _player_id = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(8, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> player_id
    {
      get { return _player_id; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _player_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> player_name
    {
      get { return _player_name; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}