//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CSPointsRaceFightData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPointsRaceFightData")]
  public partial class CSPointsRaceFightData : global::ProtoBuf.IExtensible
  {
    public CSPointsRaceFightData() {}
    
    private uint _my_old_points;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"my_old_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_old_points
    {
      get { return _my_old_points; }
      set { _my_old_points = value; }
    }
    private uint _his_rank;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"his_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint his_rank
    {
      get { return _his_rank; }
      set { _his_rank = value; }
    }
    private uint _add_honor;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"add_honor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint add_honor
    {
      get { return _add_honor; }
      set { _add_honor = value; }
    }
    private uint _continues_wins;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"continues_wins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint continues_wins
    {
      get { return _continues_wins; }
      set { _continues_wins = value; }
    }
    private uint _fight_times;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"fight_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_times
    {
      get { return _fight_times; }
      set { _fight_times = value; }
    }
    private uint _win_times;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint win_times
    {
      get { return _win_times; }
      set { _win_times = value; }
    }

    private uint _his_roleid = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"his_roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint his_roleid
    {
      get { return _his_roleid; }
      set { _his_roleid = value; }
    }
    private uint _my_old_rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"my_old_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_old_rank
    {
      get { return _my_old_rank; }
      set { _my_old_rank = value; }
    }
    private uint _my_new_points;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"my_new_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_new_points
    {
      get { return _my_new_points; }
      set { _my_new_points = value; }
    }
    private uint _my_new_rank;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"my_new_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint my_new_rank
    {
      get { return _my_new_rank; }
      set { _my_new_rank = value; }
    }
    private string _my_server;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"my_server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string my_server
    {
      get { return _my_server; }
      set { _my_server = value; }
    }
    private uint _his_level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"his_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint his_level
    {
      get { return _his_level; }
      set { _his_level = value; }
    }
    private string _his_server;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"his_server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string his_server
    {
      get { return _his_server; }
      set { _his_server = value; }
    }
    private string _his_name;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"his_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string his_name
    {
      get { return _his_name; }
      set { _his_name = value; }
    }
    private uint _his_points;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"his_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint his_points
    {
      get { return _his_points; }
      set { _his_points = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}