//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DrawLuckPackageRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawLuckPackageRequest")]
  public partial class DrawLuckPackageRequest : global::ProtoBuf.IExtensible
  {
    public DrawLuckPackageRequest() {}
    
    private uint _isdef;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint isdef
    {
      get { return _isdef; }
      set { _isdef = value; }
    }
    private uint _act_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"act_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint act_id
    {
      get { return _act_id; }
      set { _act_id = value; }
    }
    private uint _cfg_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cfg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cfg_id
    {
      get { return _cfg_id; }
      set { _cfg_id = value; }
    }
    private uint _package_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"package_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint package_id
    {
      get { return _package_id; }
      set { _package_id = value; }
    }
    private uint _drop_cfg_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"drop_cfg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint drop_cfg_id
    {
      get { return _drop_cfg_id; }
      set { _drop_cfg_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}