//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EatCucumberAnswer.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EatCucumberAnswer")]
  public partial class EatCucumberAnswer : global::ProtoBuf.IExtensible
  {
    public EatCucumberAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _power;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint power
    {
      get { return _power; }
      set { _power = value; }
    }
    private uint _yuanbao;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"yuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint yuanbao
    {
      get { return _yuanbao; }
      set { _yuanbao = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}