//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FightRound.proto
// Note: requires additional types generated from: AttackData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightRound")]
  public partial class FightRound : global::ProtoBuf.IExtensible
  {
    public FightRound() {}
    
    private readonly global::System.Collections.Generic.List<AttackData> _attack = new global::System.Collections.Generic.List<AttackData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AttackData> attack
    {
      get { return _attack; }
    }
  
    private readonly global::System.Collections.Generic.List<AttackData> _attackPre = new global::System.Collections.Generic.List<AttackData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attackPre", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AttackData> attackPre
    {
      get { return _attackPre; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}