//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildCommitRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildCommitRequest")]
  public partial class GuildCommitRequest : global::ProtoBuf.IExtensible
  {
    public GuildCommitRequest() {}
    
    private uint _idx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint idx
    {
      get { return _idx; }
      set { _idx = value; }
    }

    private uint _exception = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exception", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exception
    {
      get { return _exception; }
      set { _exception = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}