//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: HeroCheerRequest.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroCheerRequest")]
  public partial class HeroCheerRequest : global::ProtoBuf.IExtensible
  {
    public HeroCheerRequest() {}
    
    private U64Type _curGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"curGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type curGuid
    {
      get { return _curGuid; }
      set { _curGuid = value; }
    }
    private uint _slot;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}