//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: KingFightUseItemAnswer.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KingFightUseItemAnswer")]
  public partial class KingFightUseItemAnswer : global::ProtoBuf.IExtensible
  {
    public KingFightUseItemAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _item_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private uint _item_use_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"item_use_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item_use_num
    {
      get { return _item_use_num; }
      set { _item_use_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}