//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LegionChangeLogoRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LegionChangeLogoRequest")]
  public partial class LegionChangeLogoRequest : global::ProtoBuf.IExtensible
  {
    public LegionChangeLogoRequest() {}
    
    private uint _logo_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"logo_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint logo_id
    {
      get { return _logo_id; }
      set { _logo_id = value; }
    }
    private uint _frame_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"frame_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint frame_id
    {
      get { return _frame_id; }
      set { _frame_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}