//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LegionOperateRequest.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LegionOperateRequest")]
  public partial class LegionOperateRequest : global::ProtoBuf.IExtensible
  {
    public LegionOperateRequest() {}
    
    private U64Type _playerid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}