//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ListBagAnswer.proto
// Note: requires additional types generated from: BagItemProp.proto
// Note: requires additional types generated from: EquipProp.proto
// Note: requires additional types generated from: TreasureProp.proto
// Note: requires additional types generated from: FashionProp.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListBagAnswer")]
  public partial class ListBagAnswer : global::ProtoBuf.IExtensible
  {
    public ListBagAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _bagType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bagType
    {
      get { return _bagType; }
      set { _bagType = value; }
    }
    private readonly global::System.Collections.Generic.List<BagItemProp> _item = new global::System.Collections.Generic.List<BagItemProp>();
    [global::ProtoBuf.ProtoMember(3, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BagItemProp> item
    {
      get { return _item; }
    }
  
    private readonly global::System.Collections.Generic.List<EquipProp> _equip = new global::System.Collections.Generic.List<EquipProp>();
    [global::ProtoBuf.ProtoMember(4, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipProp> equip
    {
      get { return _equip; }
    }
  
    private readonly global::System.Collections.Generic.List<TreasureProp> _treasure = new global::System.Collections.Generic.List<TreasureProp>();
    [global::ProtoBuf.ProtoMember(5, Name=@"treasure", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TreasureProp> treasure
    {
      get { return _treasure; }
    }
  
    private readonly global::System.Collections.Generic.List<FashionProp> _fashion = new global::System.Collections.Generic.List<FashionProp>();
    [global::ProtoBuf.ProtoMember(6, Name=@"fashion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FashionProp> fashion
    {
      get { return _fashion; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}