//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoggerNotify.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoggerNotify")]
  public partial class LoggerNotify : global::ProtoBuf.IExtensible
  {
    public LoggerNotify() {}
    
    private readonly global::System.Collections.Generic.List<uint> _magic_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"magic_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> magic_id
    {
      get { return _magic_id; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num6 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(10, Name=@"ext_num6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num6
    {
      get { return _ext_num6; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num7 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(11, Name=@"ext_num7", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num7
    {
      get { return _ext_num7; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num8 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(12, Name=@"ext_num8", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num8
    {
      get { return _ext_num8; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num9 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(13, Name=@"ext_num9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num9
    {
      get { return _ext_num9; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num10 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(14, Name=@"ext_num10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num10
    {
      get { return _ext_num10; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ext_str1 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(15, Name=@"ext_str1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ext_str1
    {
      get { return _ext_str1; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ext_str2 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(16, Name=@"ext_str2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ext_str2
    {
      get { return _ext_str2; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ext_str3 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(17, Name=@"ext_str3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ext_str3
    {
      get { return _ext_str3; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ext_str4 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(18, Name=@"ext_str4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ext_str4
    {
      get { return _ext_str4; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ext_str5 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(19, Name=@"ext_str5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ext_str5
    {
      get { return _ext_str5; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _magic_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"magic_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> magic_type
    {
      get { return _magic_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _magic_sub_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"magic_sub_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> magic_sub_type
    {
      get { return _magic_sub_type; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _id = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(4, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> id
    {
      get { return _id; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num1 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ext_num1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num1
    {
      get { return _ext_num1; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num2 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(6, Name=@"ext_num2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num2
    {
      get { return _ext_num2; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num3 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(7, Name=@"ext_num3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num3
    {
      get { return _ext_num3; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num4 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(8, Name=@"ext_num4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num4
    {
      get { return _ext_num4; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _ext_num5 = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(9, Name=@"ext_num5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> ext_num5
    {
      get { return _ext_num5; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}