//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MailGetItemRequest.proto
// Note: requires additional types generated from: U64Type.proto
// Note: requires additional types generated from: MailData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailGetItemRequest")]
  public partial class MailGetItemRequest : global::ProtoBuf.IExtensible
  {
    public MailGetItemRequest() {}
    
    private readonly global::System.Collections.Generic.List<U64Type> _mail_id = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> mail_id
    {
      get { return _mail_id; }
    }
  
    private readonly global::System.Collections.Generic.List<MailData> _data = new global::System.Collections.Generic.List<MailData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MailData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}