//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OnFightLst.proto
// Note: requires additional types generated from: OnFightItem.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnFightLst")]
  public partial class OnFightLst : global::ProtoBuf.IExtensible
  {
    public OnFightLst() {}
    
    private readonly global::System.Collections.Generic.List<OnFightItem> _allfighters = new global::System.Collections.Generic.List<OnFightItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"allfighters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OnFightItem> allfighters
    {
      get { return _allfighters; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}