//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ShenjiangShopAnswer.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShenjiangShopAnswer")]
  public partial class ShenjiangShopAnswer : global::ProtoBuf.IExtensible
  {
    public ShenjiangShopAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _freeRefreshCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"freeRefreshCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint freeRefreshCount
    {
      get { return _freeRefreshCount; }
      set { _freeRefreshCount = value; }
    }
    private uint _freeRefreshCD;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"freeRefreshCD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint freeRefreshCD
    {
      get { return _freeRefreshCD; }
      set { _freeRefreshCD = value; }
    }
    private uint _refreshCountLimit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"refreshCountLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint refreshCountLimit
    {
      get { return _refreshCountLimit; }
      set { _refreshCountLimit = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _merchandiseId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"merchandiseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> merchandiseId
    {
      get { return _merchandiseId; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _sold_out = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"sold_out", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> sold_out
    {
      get { return _sold_out; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}