//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StageInfoPlayerInfo.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageInfoPlayerInfo")]
  public partial class StageInfoPlayerInfo : global::ProtoBuf.IExtensible
  {
    public StageInfoPlayerInfo() {}
    
    private U64Type _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _main_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"main_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint main_id
    {
      get { return _main_id; }
      set { _main_id = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _fight_power;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fight_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_power
    {
      get { return _fight_power; }
      set { _fight_power = value; }
    }
    private uint _hp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private uint _totalHp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"totalHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint totalHp
    {
      get { return _totalHp; }
      set { _totalHp = value; }
    }

    private uint _fashion_id = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}