//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TurntableRefreshAnswer.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TurntableRefreshAnswer")]
  public partial class TurntableRefreshAnswer : global::ProtoBuf.IExtensible
  {
    public TurntableRefreshAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _today_refresh_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"today_refresh_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint today_refresh_count
    {
      get { return _today_refresh_count; }
      set { _today_refresh_count = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _group_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"group_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> group_ids
    {
      get { return _group_ids; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _draw_flags = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"draw_flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> draw_flags
    {
      get { return _draw_flags; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _recommends = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"recommends", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> recommends
    {
      get { return _recommends; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_types = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"item_types", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_types
    {
      get { return _item_types; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"item_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_ids
    {
      get { return _item_ids; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_nums = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"item_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_nums
    {
      get { return _item_nums; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}