//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: VisitInfoRandomAnswer.proto
// Note: requires additional types generated from: U64Type.proto
// Note: requires additional types generated from: VisitRouteInfo.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VisitInfoRandomAnswer")]
  public partial class VisitInfoRandomAnswer : global::ProtoBuf.IExtensible
  {
    public VisitInfoRandomAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private U64Type _player_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<VisitRouteInfo> _routes = new global::System.Collections.Generic.List<VisitRouteInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"routes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<VisitRouteInfo> routes
    {
      get { return _routes; }
    }
  
    private uint _lv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private uint _history_fight_power;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"history_fight_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint history_fight_power
    {
      get { return _history_fight_power; }
      set { _history_fight_power = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}