//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ZhuZhenItem.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZhuZhenItem")]
  public partial class ZhuZhenItem : global::ProtoBuf.IExtensible
  {
    public ZhuZhenItem() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private U64Type _uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _fightpos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fightpos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fightpos
    {
      get { return _fightpos; }
      set { _fightpos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}