//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ArenaStartServerRequest.proto
// Note: requires additional types generated from: PlayerInfo.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaStartServerRequest")]
  public partial class ArenaStartServerRequest : global::ProtoBuf.IExtensible
  {
    public ArenaStartServerRequest() {}
    
    private uint _selfRank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"selfRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint selfRank
    {
      get { return _selfRank; }
      set { _selfRank = value; }
    }
    private uint _peerRank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"peerRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint peerRank
    {
      get { return _peerRank; }
      set { _peerRank = value; }
    }
    private PlayerInfo _peerinfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"peerinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerInfo peerinfo
    {
      get { return _peerinfo; }
      set { _peerinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}