//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuyWudiFightCntAnswer.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyWudiFightCntAnswer")]
  public partial class BuyWudiFightCntAnswer : global::ProtoBuf.IExtensible
  {
    public BuyWudiFightCntAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint _boss_ts;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"boss_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint boss_ts
    {
      get { return _boss_ts; }
      set { _boss_ts = value; }
    }
    private uint _fight_cnt;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fight_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_cnt
    {
      get { return _fight_cnt; }
      set { _fight_cnt = value; }
    }
    private uint _total_buy_fight_cnt;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"total_buy_fight_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint total_buy_fight_cnt
    {
      get { return _total_buy_fight_cnt; }
      set { _total_buy_fight_cnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}