//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CardProp.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardProp")]
  public partial class CardProp : global::ProtoBuf.IExtensible
  {
    public CardProp() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _addattack;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"addattack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint addattack
    {
      get { return _addattack; }
      set { _addattack = value; }
    }
    private uint _adddefphy;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"adddefphy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint adddefphy
    {
      get { return _adddefphy; }
      set { _adddefphy = value; }
    }
    private uint _adddefmag;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"adddefmag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint adddefmag
    {
      get { return _adddefmag; }
      set { _adddefmag = value; }
    }
    private U64Type _uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _exp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _color;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint color
    {
      get { return _color; }
      set { _color = value; }
    }
    private uint _zizhi;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"zizhi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zizhi
    {
      get { return _zizhi; }
      set { _zizhi = value; }
    }
    private uint _tupo;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"tupo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tupo
    {
      get { return _tupo; }
      set { _tupo = value; }
    }
    private uint _tianming;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"tianming", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tianming
    {
      get { return _tianming; }
      set { _tianming = value; }
    }
    private uint _xingji;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"xingji", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint xingji
    {
      get { return _xingji; }
      set { _xingji = value; }
    }
    private uint _addhp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"addhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint addhp
    {
      get { return _addhp; }
      set { _addhp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}