//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChatMsgNotify.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMsgNotify")]
  public partial class ChatMsgNotify : global::ProtoBuf.IExtensible
  {
    public ChatMsgNotify() {}
    
    private uint _channel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channel
    {
      get { return _channel; }
      set { _channel = value; }
    }

    private U64Type _sender_legion_id = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"sender_legion_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U64Type sender_legion_id
    {
      get { return _sender_legion_id; }
      set { _sender_legion_id = value; }
    }

    private string _sender_legion_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"sender_legion_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sender_legion_name
    {
      get { return _sender_legion_name; }
      set { _sender_legion_name = value; }
    }
    private string _sender_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private uint _mainrole_card_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mainrole_card_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mainrole_card_id
    {
      get { return _mainrole_card_id; }
      set { _mainrole_card_id = value; }
    }
    private uint _vip_level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }

    private uint _fashion_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }

    private U64Type _sender_id = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public U64Type sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }

    private uint _sender_lv = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sender_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sender_lv
    {
      get { return _sender_lv; }
      set { _sender_lv = value; }
    }

    private uint _sender_fc = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sender_fc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sender_fc
    {
      get { return _sender_fc; }
      set { _sender_fc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}