//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChoukaAnswer.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChoukaAnswer")]
  public partial class ChoukaAnswer : global::ProtoBuf.IExtensible
  {
    public ChoukaAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _item_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_type
    {
      get { return _item_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_id
    {
      get { return _item_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_count = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(12, Name=@"item_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_count
    {
      get { return _item_count; }
    }
  
    private readonly global::System.Collections.Generic.List<U64Type> _item_guid = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(13, Name=@"item_guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> item_guid
    {
      get { return _item_guid; }
    }
  

    private uint _luck = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"luck", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint luck
    {
      get { return _luck; }
      set { _luck = value; }
    }

    private uint _luck_change = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"luck_change", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint luck_change
    {
      get { return _luck_change; }
      set { _luck_change = value; }
    }

    private uint _luck_crits = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"luck_crits", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint luck_crits
    {
      get { return _luck_crits; }
      set { _luck_crits = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _item_luck_add = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(17, Name=@"item_luck_add", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_luck_add
    {
      get { return _item_luck_add; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_luck_crit = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(18, Name=@"item_luck_crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_luck_crit
    {
      get { return _item_luck_crit; }
    }
  
    private uint _isdef;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint isdef
    {
      get { return _isdef; }
      set { _isdef = value; }
    }
    private uint _act_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"act_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint act_id
    {
      get { return _act_id; }
      set { _act_id = value; }
    }
    private uint _cfg_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"cfg_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cfg_id
    {
      get { return _cfg_id; }
      set { _cfg_id = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _free_count;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"free_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint free_count
    {
      get { return _free_count; }
      set { _free_count = value; }
    }
    private uint _freecd;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"freecd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint freecd
    {
      get { return _freecd; }
      set { _freecd = value; }
    }
    private uint _node_id;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"node_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint node_id
    {
      get { return _node_id; }
      set { _node_id = value; }
    }
    private uint _left_count;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"left_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_count
    {
      get { return _left_count; }
      set { _left_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}