//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CrusadeFortressOpenBoxRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CrusadeFortressOpenBoxRequest")]
  public partial class CrusadeFortressOpenBoxRequest : global::ProtoBuf.IExtensible
  {
    public CrusadeFortressOpenBoxRequest() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _idx;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint idx
    {
      get { return _idx; }
      set { _idx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}