//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CsGrouponInfoAnswer.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CsGrouponInfoAnswer")]
  public partial class CsGrouponInfoAnswer : global::ProtoBuf.IExtensible
  {
    public CsGrouponInfoAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _total_count;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"total_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint total_count
    {
      get { return _total_count; }
      set { _total_count = value; }
    }
    private uint _left_count;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"left_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_count
    {
      get { return _left_count; }
      set { _left_count = value; }
    }
    private uint _self_count;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"self_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint self_count
    {
      get { return _self_count; }
      set { _self_count = value; }
    }

    private string _winner_name = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"winner_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string winner_name
    {
      get { return _winner_name; }
      set { _winner_name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _rank = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(17, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> rank
    {
      get { return _rank; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(18, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _count = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(19, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> count
    {
      get { return _count; }
    }
  
    private uint _limit_ts;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"limit_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint limit_ts
    {
      get { return _limit_ts; }
      set { _limit_ts = value; }
    }
    private uint _award_ts;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"award_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint award_ts
    {
      get { return _award_ts; }
      set { _award_ts = value; }
    }
    private uint _end_ts;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"end_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint end_ts
    {
      get { return _end_ts; }
      set { _end_ts = value; }
    }
    private uint _id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _recharge_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"recharge_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint recharge_id
    {
      get { return _recharge_id; }
      set { _recharge_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}