//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CsRiverLanternSelfRankUpdateNotify.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CsRiverLanternSelfRankUpdateNotify")]
  public partial class CsRiverLanternSelfRankUpdateNotify : global::ProtoBuf.IExtensible
  {
    public CsRiverLanternSelfRankUpdateNotify() {}
    
    private uint _self_rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"self_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint self_rank
    {
      get { return _self_rank; }
      set { _self_rank = value; }
    }
    private uint _self_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"self_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint self_count
    {
      get { return _self_count; }
      set { _self_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}