//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FenjieRequest.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FenjieRequest")]
  public partial class FenjieRequest : global::ProtoBuf.IExtensible
  {
    public FenjieRequest() {}
    
    private readonly global::System.Collections.Generic.List<U64Type> _uuid = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(1, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> uuid
    {
      get { return _uuid; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _pos = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> pos
    {
      get { return _pos; }
    }
  
    private uint _recycle_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"recycle_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint recycle_type
    {
      get { return _recycle_type; }
      set { _recycle_type = value; }
    }
    private uint _content_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"content_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint content_type
    {
      get { return _content_type; }
      set { _content_type = value; }
    }
    private uint _step;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}