//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FighterStatu.proto
// Note: requires additional types generated from: I64Type.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FighterStatu")]
  public partial class FighterStatu : global::ProtoBuf.IExtensible
  {
    public FighterStatu() {}
    
    private uint _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _attacked;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"attacked", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint attacked
    {
      get { return _attacked; }
      set { _attacked = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _buffAnger = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"buffAnger", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> buffAnger
    {
      get { return _buffAnger; }
    }
  

    private I64Type _reboundHp = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"reboundHp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public I64Type reboundHp
    {
      get { return _reboundHp; }
      set { _reboundHp = value; }
    }

    private uint _roleid = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }

    private uint _roletype = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"roletype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roletype
    {
      get { return _roletype; }
      set { _roletype = value; }
    }

    private uint _rolefashion = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"rolefashion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rolefashion
    {
      get { return _rolefashion; }
      set { _rolefashion = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _buffNoEffect = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(17, Name=@"buffNoEffect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> buffNoEffect
    {
      get { return _buffNoEffect; }
    }
  
    private U64Type _hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private U64Type _hptotal;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hptotal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type hptotal
    {
      get { return _hptotal; }
      set { _hptotal = value; }
    }
    private uint _anger;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"anger", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint anger
    {
      get { return _anger; }
      set { _anger = value; }
    }
    private uint _skillAnger;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"skillAnger", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillAnger
    {
      get { return _skillAnger; }
      set { _skillAnger = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _buffs = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"buffs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> buffs
    {
      get { return _buffs; }
    }
  
    private I64Type _skillHp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"skillHp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public I64Type skillHp
    {
      get { return _skillHp; }
      set { _skillHp = value; }
    }
    private readonly global::System.Collections.Generic.List<I64Type> _buffHp = new global::System.Collections.Generic.List<I64Type>();
    [global::ProtoBuf.ProtoMember(8, Name=@"buffHp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<I64Type> buffHp
    {
      get { return _buffHp; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _buffDelete = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"buffDelete", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> buffDelete
    {
      get { return _buffDelete; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}