//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FortressFightRecordData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FortressFightRecordData")]
  public partial class FortressFightRecordData : global::ProtoBuf.IExtensible
  {
    public FortressFightRecordData() {}
    
    private uint _fortress_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fortress_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fortress_id
    {
      get { return _fortress_id; }
      set { _fortress_id = value; }
    }
    private ulong _occupant_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"occupant_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong occupant_id
    {
      get { return _occupant_id; }
      set { _occupant_id = value; }
    }
    private ulong _record_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"record_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong record_id
    {
      get { return _record_id; }
      set { _record_id = value; }
    }
    private ulong _player_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _player_name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private uint _fight_power;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fight_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_power
    {
      get { return _fight_power; }
      set { _fight_power = value; }
    }
    private uint _role_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private string _legion_name;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"legion_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string legion_name
    {
      get { return _legion_name; }
      set { _legion_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}