//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FriendRecvEnergyAnswer.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendRecvEnergyAnswer")]
  public partial class FriendRecvEnergyAnswer : global::ProtoBuf.IExtensible
  {
    public FriendRecvEnergyAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<U64Type> _playerid = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> playerid
    {
      get { return _playerid; }
    }
  
    private uint _energy_recv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"energy_recv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint energy_recv
    {
      get { return _energy_recv; }
      set { _energy_recv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}