//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LegionBossInfoAnswer.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LegionBossInfoAnswer")]
  public partial class LegionBossInfoAnswer : global::ProtoBuf.IExtensible
  {
    public LegionBossInfoAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private U64Type _max_damage;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"max_damage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type max_damage
    {
      get { return _max_damage; }
      set { _max_damage = value; }
    }
    private uint _fight_stage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fight_stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_stage
    {
      get { return _fight_stage; }
      set { _fight_stage = value; }
    }
    private uint _cycle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cycle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cycle
    {
      get { return _cycle; }
      set { _cycle = value; }
    }
    private uint _stage;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
    private uint _boss_hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"boss_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint boss_hp
    {
      get { return _boss_hp; }
      set { _boss_hp = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _reward = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward
    {
      get { return _reward; }
    }
  
    private uint _rank;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private uint _left_count;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"left_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_count
    {
      get { return _left_count; }
      set { _left_count = value; }
    }
    private uint _next_fight_ts;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"next_fight_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_fight_ts
    {
      get { return _next_fight_ts; }
      set { _next_fight_ts = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}