//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LegionChangeAcceptTypeRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LegionChangeAcceptTypeRequest")]
  public partial class LegionChangeAcceptTypeRequest : global::ProtoBuf.IExtensible
  {
    public LegionChangeAcceptTypeRequest() {}
    
    private uint _accept_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accept_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint accept_type
    {
      get { return _accept_type; }
      set { _accept_type = value; }
    }
    private uint _accept_value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accept_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint accept_value
    {
      get { return _accept_value; }
      set { _accept_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}