//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LevelUpNotify.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelUpNotify")]
  public partial class LevelUpNotify : global::ProtoBuf.IExtensible
  {
    public LevelUpNotify() {}
    
    private uint _pre_level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pre_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pre_level
    {
      get { return _pre_level; }
      set { _pre_level = value; }
    }
    private uint _pre_vigor;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pre_vigor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pre_vigor
    {
      get { return _pre_vigor; }
      set { _pre_vigor = value; }
    }
    private uint _pre_energy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pre_energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pre_energy
    {
      get { return _pre_energy; }
      set { _pre_energy = value; }
    }
    private uint _current_level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"current_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_level
    {
      get { return _current_level; }
      set { _current_level = value; }
    }
    private uint _current_vigor;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"current_vigor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_vigor
    {
      get { return _current_vigor; }
      set { _current_vigor = value; }
    }
    private uint _current_energy;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"current_energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_energy
    {
      get { return _current_energy; }
      set { _current_energy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}