//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MailSendRequest.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailSendRequest")]
  public partial class MailSendRequest : global::ProtoBuf.IExtensible
  {
    public MailSendRequest() {}
    
    private U64Type _recv_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"recv_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type recv_id
    {
      get { return _recv_id; }
      set { _recv_id = value; }
    }
    private U64Type _sender_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }
    private string _sender_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _context;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}