//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MainRaidSweepAnswer.proto
// Note: requires additional types generated from: SweepRewardData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainRaidSweepAnswer")]
  public partial class MainRaidSweepAnswer : global::ProtoBuf.IExtensible
  {
    public MainRaidSweepAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _res;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint res
    {
      get { return _res; }
      set { _res = value; }
    }
    private uint _raid_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"raid_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint raid_id
    {
      get { return _raid_id; }
      set { _raid_id = value; }
    }
    private uint _apply_cnt;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"apply_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint apply_cnt
    {
      get { return _apply_cnt; }
      set { _apply_cnt = value; }
    }
    private uint _rebel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rebel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rebel
    {
      get { return _rebel; }
      set { _rebel = value; }
    }
    private uint _sure_cnt;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sure_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sure_cnt
    {
      get { return _sure_cnt; }
      set { _sure_cnt = value; }
    }
    private readonly global::System.Collections.Generic.List<SweepRewardData> _data = new global::System.Collections.Generic.List<SweepRewardData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SweepRewardData> data
    {
      get { return _data; }
    }
  

    private uint _new_rebel = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"new_rebel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint new_rebel
    {
      get { return _new_rebel; }
      set { _new_rebel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}