//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ModuleSubscribeRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModuleSubscribeRequest")]
  public partial class ModuleSubscribeRequest : global::ProtoBuf.IExtensible
  {
    public ModuleSubscribeRequest() {}
    
    private uint _subscribe_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"subscribe_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subscribe_id
    {
      get { return _subscribe_id; }
      set { _subscribe_id = value; }
    }
    private uint _unsubscribe;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unsubscribe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint unsubscribe
    {
      get { return _unsubscribe; }
      set { _unsubscribe = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}