//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OpenSrvRankActivityInfo.proto
// Note: requires additional types generated from: OpenSrvRankPlayerInfo.proto
// Note: requires additional types generated from: OpenSrvRankAwardInfo.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenSrvRankActivityInfo")]
  public partial class OpenSrvRankActivityInfo : global::ProtoBuf.IExtensible
  {
    public OpenSrvRankActivityInfo() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _countdown;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"countdown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint countdown
    {
      get { return _countdown; }
      set { _countdown = value; }
    }
    private string _end_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _fight_power;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fight_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_power
    {
      get { return _fight_power; }
      set { _fight_power = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenSrvRankPlayerInfo> _players = new global::System.Collections.Generic.List<OpenSrvRankPlayerInfo>();
    [global::ProtoBuf.ProtoMember(7, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenSrvRankPlayerInfo> players
    {
      get { return _players; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenSrvRankAwardInfo> _rank_award = new global::System.Collections.Generic.List<OpenSrvRankAwardInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"rank_award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenSrvRankAwardInfo> rank_award
    {
      get { return _rank_award; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenSrvRankAwardInfo> _fight_power_award = new global::System.Collections.Generic.List<OpenSrvRankAwardInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"fight_power_award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenSrvRankAwardInfo> fight_power_award
    {
      get { return _fight_power_award; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}