//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OpenSrvRankAwardInfo.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenSrvRankAwardInfo")]
  public partial class OpenSrvRankAwardInfo : global::ProtoBuf.IExtensible
  {
    public OpenSrvRankAwardInfo() {}
    
    private uint _cond1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cond1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cond1
    {
      get { return _cond1; }
      set { _cond1 = value; }
    }
    private uint _cond2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cond2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cond2
    {
      get { return _cond2; }
      set { _cond2 = value; }
    }
    private uint _flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> type
    {
      get { return _type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> id
    {
      get { return _id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> num
    {
      get { return _num; }
    }
  

    private uint _rank_end = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rank_end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank_end
    {
      get { return _rank_end; }
      set { _rank_end = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}