//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OpenUIReport.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpenUIReport")]
  public partial class OpenUIReport : global::ProtoBuf.IExtensible
  {
    public OpenUIReport() {}
    
    private uint _ui_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ui_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ui_id
    {
      get { return _ui_id; }
      set { _ui_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}