//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PetRaidInfoAnswer.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PetRaidInfoAnswer")]
  public partial class PetRaidInfoAnswer : global::ProtoBuf.IExtensible
  {
    public PetRaidInfoAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _raid_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"raid_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint raid_id
    {
      get { return _raid_id; }
      set { _raid_id = value; }
    }
    private uint _left_count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"left_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_count
    {
      get { return _left_count; }
      set { _left_count = value; }
    }
    private uint _reset_count;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"reset_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reset_count
    {
      get { return _reset_count; }
      set { _reset_count = value; }
    }
    private uint _day_of_week;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"day_of_week", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint day_of_week
    {
      get { return _day_of_week; }
      set { _day_of_week = value; }
    }
    private uint _no_failure_record_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"no_failure_record_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint no_failure_record_id
    {
      get { return _no_failure_record_id; }
      set { _no_failure_record_id = value; }
    }
    private uint _used_one_key_pass;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"used_one_key_pass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint used_one_key_pass
    {
      get { return _used_one_key_pass; }
      set { _used_one_key_pass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}