//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerInfo.proto
// Note: requires additional types generated from: U64Type.proto
// Note: requires additional types generated from: CardAttrData.proto
// Note: requires additional types generated from: EquipProp.proto
// Note: requires additional types generated from: TreasureProp.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private U64Type _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _cheer = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"cheer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> cheer
    {
      get { return _cheer; }
    }
  
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _attr = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> attr
    {
      get { return _attr; }
    }
  
    private readonly global::System.Collections.Generic.List<CardAttrData> _card = new global::System.Collections.Generic.List<CardAttrData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CardAttrData> card
    {
      get { return _card; }
    }
  
    private readonly global::System.Collections.Generic.List<EquipProp> _equip = new global::System.Collections.Generic.List<EquipProp>();
    [global::ProtoBuf.ProtoMember(5, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipProp> equip
    {
      get { return _equip; }
    }
  
    private readonly global::System.Collections.Generic.List<U64Type> _embattle = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(6, Name=@"embattle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> embattle
    {
      get { return _embattle; }
    }
  
    private uint _towerStar;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"towerStar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint towerStar
    {
      get { return _towerStar; }
      set { _towerStar = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _passiveSkill = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"passiveSkill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> passiveSkill
    {
      get { return _passiveSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<TreasureProp> _treasure = new global::System.Collections.Generic.List<TreasureProp>();
    [global::ProtoBuf.ProtoMember(9, Name=@"treasure", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TreasureProp> treasure
    {
      get { return _treasure; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}