//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RaidRewardRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaidRewardRequest")]
  public partial class RaidRewardRequest : global::ProtoBuf.IExtensible
  {
    public RaidRewardRequest() {}
    
    private uint _section_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"section_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint section_id
    {
      get { return _section_id; }
      set { _section_id = value; }
    }
    private uint _section_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"section_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint section_type
    {
      get { return _section_type; }
      set { _section_type = value; }
    }
    private uint _reward_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reward_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reward_type
    {
      get { return _reward_type; }
      set { _reward_type = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}