//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RebelShareFlagNotify.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RebelShareFlagNotify")]
  public partial class RebelShareFlagNotify : global::ProtoBuf.IExtensible
  {
    public RebelShareFlagNotify() {}
    
    private U64Type _serial_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serial_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type serial_id
    {
      get { return _serial_id; }
      set { _serial_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}