//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ShenjiangShopRequest.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShenjiangShopRequest")]
  public partial class ShenjiangShopRequest : global::ProtoBuf.IExtensible
  {
    public ShenjiangShopRequest() {}
    
    private uint _refresh;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"refresh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint refresh
    {
      get { return _refresh; }
      set { _refresh = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}