//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TowerLadderSweepData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TowerLadderSweepData")]
  public partial class TowerLadderSweepData : global::ProtoBuf.IExtensible
  {
    public TowerLadderSweepData() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private uint _gate;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gate
    {
      get { return _gate; }
      set { _gate = value; }
    }
    private uint _buffid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"buffid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buffid
    {
      get { return _buffid; }
      set { _buffid = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _item_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_type
    {
      get { return _item_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_id
    {
      get { return _item_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_num
    {
      get { return _item_num; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _floor_item_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"floor_item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> floor_item_type
    {
      get { return _floor_item_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _floor_item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"floor_item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> floor_item_id
    {
      get { return _floor_item_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _floor_item_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"floor_item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> floor_item_num
    {
      get { return _floor_item_num; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}