//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TowerLadderStartFloorData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TowerLadderStartFloorData")]
  public partial class TowerLadderStartFloorData : global::ProtoBuf.IExtensible
  {
    public TowerLadderStartFloorData() {}
    
    private uint _gate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gate
    {
      get { return _gate; }
      set { _gate = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _floor_item_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"floor_item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> floor_item_num
    {
      get { return _floor_item_num; }
    }
  

    private uint _defeat = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"defeat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint defeat
    {
      get { return _defeat; }
      set { _defeat = value; }
    }

    private uint _cond_value = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"cond_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cond_value
    {
      get { return _cond_value; }
      set { _cond_value = value; }
    }
    private uint _win;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint win
    {
      get { return _win; }
      set { _win = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _starcond;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"starcond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint starcond
    {
      get { return _starcond; }
      set { _starcond = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _item_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_type
    {
      get { return _item_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_id
    {
      get { return _item_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_num
    {
      get { return _item_num; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _floor_item_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"floor_item_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> floor_item_type
    {
      get { return _floor_item_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _floor_item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"floor_item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> floor_item_id
    {
      get { return _floor_item_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}