//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ViewPlayerAnswer.proto
// Note: requires additional types generated from: U64Type.proto
// Note: requires additional types generated from: ViewPlayerData.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ViewPlayerAnswer")]
  public partial class ViewPlayerAnswer : global::ProtoBuf.IExtensible
  {
    public ViewPlayerAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private uint _pet_level = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pet_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pet_level
    {
      get { return _pet_level; }
      set { _pet_level = value; }
    }

    private uint _pet_refine_lv = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"pet_refine_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pet_refine_lv
    {
      get { return _pet_refine_lv; }
      set { _pet_refine_lv = value; }
    }
    private U64Type _player_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _vip_level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _fight_power;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fight_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_power
    {
      get { return _fight_power; }
      set { _fight_power = value; }
    }
    private readonly global::System.Collections.Generic.List<ViewPlayerData> _player_data = new global::System.Collections.Generic.List<ViewPlayerData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"player_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ViewPlayerData> player_data
    {
      get { return _player_data; }
    }
  

    private uint _fashion_id = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }

    private uint _pet_id = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pet_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pet_id
    {
      get { return _pet_id; }
      set { _pet_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}