//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: VisitFriendAccelerateInfo.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VisitFriendAccelerateInfo")]
  public partial class VisitFriendAccelerateInfo : global::ProtoBuf.IExtensible
  {
    public VisitFriendAccelerateInfo() {}
    
    private U64Type _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _route_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"route_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> route_id
    {
      get { return _route_id; }
    }
  
    private uint _add_ts;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"add_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint add_ts
    {
      get { return _add_ts; }
      set { _add_ts = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}