//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: WudiHurtRankAnswer.proto
// Note: requires additional types generated from: U64Type.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WudiHurtRankAnswer")]
  public partial class WudiHurtRankAnswer : global::ProtoBuf.IExtensible
  {
    public WudiHurtRankAnswer() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _self_rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"self_rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint self_rank
    {
      get { return _self_rank; }
      set { _self_rank = value; }
    }
    private U64Type _self_hurt;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"self_hurt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type self_hurt
    {
      get { return _self_hurt; }
      set { _self_hurt = value; }
    }
    private readonly global::System.Collections.Generic.List<U64Type> _player_id = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(4, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> player_id
    {
      get { return _player_id; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _player_name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> player_name
    {
      get { return _player_name; }
    }
  
    private readonly global::System.Collections.Generic.List<U64Type> _hurt = new global::System.Collections.Generic.List<U64Type>();
    [global::ProtoBuf.ProtoMember(6, Name=@"hurt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<U64Type> hurt
    {
      get { return _hurt; }
    }
  
    private U64Type _boss_hp_limit;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"boss_hp_limit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public U64Type boss_hp_limit
    {
      get { return _boss_hp_limit; }
      set { _boss_hp_limit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}