namespace ClientServerCommon
{
    using System;

    public class _OpenFunctionType : TypeNameContainer<_OpenFunctionType>
    {
        public const int Activity = 10;
        public const int Arena = 0x12;
        public const int Assistant = 7;
        public const int AvatarBreakThrough = 0x16;
        public const int AvatarDomineer = 0x1a;
        public const int AvatarLevelUp = 14;
        public const int AvatarLevelUpOneClick = 30;
        public const int Awaken = 50;
        public const int BackPack = 2;
        public const int BattleSpeedUpX1 = 0x1f;
        public const int BattleSpeedUpX2 = 0x20;
        public const int BatUseConsumable = 0x22;
        public const int Beast = 0x3f;
        public const int Boxes = 0x2a;
        public const int CardPicture = 11;
        public const int Chat = 12;
        public const int ClearCampaignCombatWithRealmoney = 0x1b;
        public const int ContinueCombat = 0x23;
        public const int DailyQuestReward = 0x31;
        public const int DailyReward = 0x27;
        public const int DanHome = 0x3b;
        public const int Diner = 0x13;
        public const int Domineer = 3;
        public const int Dungeon = 8;
        public const int EquipmentLevelUp = 0x11;
        public const int EquipmentLevelUpOneClick = 0x1d;
        public const int EquipmentRefine = 1;
        public const int Exchange = 13;
        public const int FixedTimeActivity = 0x1c;
        public const int Friend = 0x35;
        public const int FriendCampaign = 0x38;
        public const int GetWayCompose = 0x2d;
        public const int GhostValley = 0x2e;
        public const int GoodsShop = 5;
        public const int Guild = 60;
        public const int Illusion = 0x39;
        public const int InviteCode = 0x3d;
        public const int ItemGetWay = 40;
        public const int LevelRewardActivity = 0x21;
        public const int MarvellousAdventure = 0x37;
        public const int MelaleucaFloor = 0x2b;
        public const int Meridian = 0x17;
        public const int MonthCardFeedback = 0x2c;
        public const int MysteryShop = 6;
        public const int MysteryShopRefreshByNationality = 0x25;
        public const int OneClickPositionOff = 0x3a;
        public const int Partner = 0x15;
        public const int Purchase = 0x24;
        public const int QinInfo = 0x34;
        public const int Reincarnation = 0x30;
        public const int RetainOriginalDomineerSkill = 0x26;
        public const int Secret = 20;
        public const int SkillLevelUp = 0x19;
        public const int SkyCombat = 0x2f;
        public const int StartServerReward = 0x3e;
        public const int Tavern = 15;
        public const int TravelGuid = 0x36;
        public const int TravelTrader = 4;
        public const int TreasureBowl = 0x29;
        public const int Unknown = 0;
        public const int UnsaveAvatarDomineer = 0x18;
        public const int Vip = 9;
        public const int WolfSmoke = 0x33;

        public static bool Initialize()
        {
            bool flag = false;
            TypeNameContainer<_OpenFunctionType>.SetTextSectionName("OpenFunctionType");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("EquipmentRefine", 1, "UI_Function_EquipmentRefine");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("BackPack", 2, "UI_Function_BackPack");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Domineer", 3, "UI_Function_Domineer");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("TravelTrader", 4, "UI_Function_TravelTrader");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("GoodsShop", 5, "UI_Function_GoodsShop");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("MysteryShop", 6, "UI_Function_MysteryShop");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Assistant", 7, "UI_Function_Assistant");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Dungeon", 8, "UI_Function_Dungeon");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Vip", 9, "UI_Function_Vip");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Activity", 10, "UI_Function_Activity");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("CardPicture", 11, "UI_Function_CardPicture");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Chat", 12, "UI_Function_Chat");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Exchange", 13, "UI_Function_Exchange");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("AvatarLevelUp", 14, "UI_Function_AvatarLevelUp");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Tavern", 15, "UI_Function_Tavern");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("EquipmentLevelUp", 0x11, "UI_Function_EquipmentLevelUp");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Arena", 0x12, "UI_Function_Arena");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Diner", 0x13, "UI_Function_Diner");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Secret", 20, "UI_Function_Secret");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Partner", 0x15, "UI_Function_Partner");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("AvatarBreakThrough", 0x16, "UI_Function_AvatarBreakThrough");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Meridian", 0x17, "UI_Function_Meridian");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("UnsaveAvatarDomineer", 0x18, "UI_Function_UnsaveAvatarDomineer");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("SkillLevelUp", 0x19, "UI_Function_SkillLevelUp");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("AvatarDomineer", 0x1a, "UI_Function_AvatarDomineer");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("ClearCampaignCombatWithRealmoney", 0x1b, "UI_Function_ClearCampaignCombatWithRealmoney");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("FixedTimeActivity", 0x1c, "UI_Function_FixedTimeActivity");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("EquipmentLevelUpOneClick", 0x1d, "UI_Function_EquipmentLevelUpOneClick");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("AvatarLevelUpOneClick", 30, "UI_Function_AvatarLevelUpOneClick");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("BattleSpeedUpX1", 0x1f, "UI_Function_BattleSpeedUpX1");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("BattleSpeedUpX2", 0x20, "UI_Function_BattleSpeedUpX2");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("LevelRewardActivity", 0x21, "UI_Function_LevelRewardActivity");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("BatUseConsumable", 0x22, "UI_Function_BatUseConsumable");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("ContinueCombat", 0x23, "UI_Function_ContinueCombat");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Purchase", 0x24, "UI_Function_Purchase");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("MysteryShopRefreshByNationality", 0x25, "UI_Function_MysteryShopRefreshByNationality");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("RetainOriginalDomineerSkill", 0x26, "UI_Function_RetainOriginalDomineerSkill");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("DailyReward", 0x27, "UI_Function_DailyReward");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("ItemGetWay", 40, "UI_Function_ItemGetWay");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("TreasureBowl", 0x29, "UI_Function_TreasureBowl");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Boxes", 0x2a, "UI_Function_Boxes");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("MelaleucaFloor", 0x2b, "UI_Function_MelaleucaFloor");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("MonthCardFeedback", 0x2c, "UI_Function_MonthCardFeedback");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("GetWayCompose", 0x2d, "UI_Function_GetWayCompose");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("GhostValley", 0x2e, "UI_Function_GhostValley");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("SkyCombat", 0x2f, "UI_Function_SkyCombat");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Reincarnation", 0x30, "UI_Function_Reincarnation");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("DailyQuestReward", 0x31, "UI_Function_DailyQuestReward");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Awaken", 50, "UI_Function_Awaken");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("WolfSmoke", 0x33, "UI_Function_WolfSmoke");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("QinInfo", 0x34, "UI_Function_QinInfo");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Friend", 0x35, "UI_Function_Friend");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("TravelGuid", 0x36, "UI_Function_TravelGuid");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("MarvellousAdventure", 0x37, "UI_Function_MarvellousAdventure");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("FriendCampaign", 0x38, "FriendCampaign");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Illusion", 0x39, "UI_Function_Illusion");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("InviteCode", 0x3d, "UI_Function_InviteCode");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("StartServerReward", 0x3e, "UI_Function_StartServerReward");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("OneClickPositionOff", 0x3a, "");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("DanHome", 0x3b, "UI_Function_DanHome");
            flag &= TypeNameContainer<_OpenFunctionType>.RegisterType("Guild", 60, "UI_Function_Guild");
            return (flag & TypeNameContainer<_OpenFunctionType>.RegisterType("Beast", 0x3f, "UI_Function_Beast"));
        }
    }
}

